var searchData=
[
  ['qrcodedetector',['QRCodeDetector',['../de/dc3/classcv_1_1QRCodeDetector.html',1,'cv']]],
  ['qrcodeencoder',['QRCodeEncoder',['../d2/dbb/classcv_1_1QRCodeEncoder.html',1,'cv']]],
  ['qtfont',['QtFont',['../d2/dbf/structcv_1_1QtFont.html',1,'cv']]],
  ['quadedge',['QuadEdge',['../d4/dbc/structcv_1_1Subdiv2D_1_1QuadEdge.html',1,'cv::Subdiv2D']]],
  ['qualitybase',['QualityBase',['../da/d83/classcv_1_1quality_1_1QualityBase.html',1,'cv::quality']]],
  ['qualitybrisque',['QualityBRISQUE',['../d8/d99/classcv_1_1quality_1_1QualityBRISQUE.html',1,'cv::quality']]],
  ['qualitygmsd',['QualityGMSD',['../d8/d81/classcv_1_1quality_1_1QualityGMSD.html',1,'cv::quality']]],
  ['qualitymse',['QualityMSE',['../d7/d80/classcv_1_1quality_1_1QualityMSE.html',1,'cv::quality']]],
  ['qualitypsnr',['QualityPSNR',['../d8/d0c/classcv_1_1quality_1_1QualityPSNR.html',1,'cv::quality']]],
  ['qualityssim',['QualitySSIM',['../d9/db5/classcv_1_1quality_1_1QualitySSIM.html',1,'cv::quality']]],
  ['quantizedpyramid',['QuantizedPyramid',['../d7/d6f/classcv_1_1linemod_1_1QuantizedPyramid.html',1,'cv::linemod']]],
  ['quantizelayer',['QuantizeLayer',['../d0/d5b/classcv_1_1dnn_1_1QuantizeLayer.html',1,'cv::dnn']]],
  ['quasidensestereo',['QuasiDenseStereo',['../dc/df4/classcv_1_1stereo_1_1QuasiDenseStereo.html',1,'cv::stereo']]],
  ['quat',['Quat',['../da/d4a/classcv_1_1Quat.html',1,'cv']]],
  ['quatenum',['QuatEnum',['../d2/d53/classcv_1_1QuatEnum.html',1,'cv']]],
  ['queue',['Queue',['../dd/dc0/classcv_1_1ocl_1_1Queue.html',1,'cv::ocl']]],
  ['queue_5fcapacity',['queue_capacity',['../d8/d5f/structcv_1_1gapi_1_1streaming_1_1queue__capacity.html',1,'cv::gapi::streaming']]]
];
