var searchData=
[
  ['facedetectoryn',['FaceDetectorYN',['../df/d20/classcv_1_1FaceDetectorYN.html',1,'cv']]],
  ['facemark',['Facemark',['../db/dd8/classcv_1_1face_1_1Facemark.html',1,'cv::face']]],
  ['facemarkaam',['FacemarkAAM',['../d5/d7b/classcv_1_1face_1_1FacemarkAAM.html',1,'cv::face']]],
  ['facemarkkazemi',['FacemarkKazemi',['../dc/de0/classcv_1_1face_1_1FacemarkKazemi.html',1,'cv::face']]],
  ['facemarklbf',['FacemarkLBF',['../dc/d63/classcv_1_1face_1_1FacemarkLBF.html',1,'cv::face']]],
  ['facemarktrain',['FacemarkTrain',['../d3/d81/classcv_1_1face_1_1FacemarkTrain.html',1,'cv::face']]],
  ['facerecognizer',['FaceRecognizer',['../dd/d65/classcv_1_1face_1_1FaceRecognizer.html',1,'cv::face']]],
  ['facerecognizersf',['FaceRecognizerSF',['../da/d09/classcv_1_1FaceRecognizerSF.html',1,'cv']]],
  ['farnebackopticalflow',['FarnebackOpticalFlow',['../dd/d00/classcv_1_1superres_1_1FarnebackOpticalFlow.html',1,'cv::superres::FarnebackOpticalFlow'],['../d9/d30/classcv_1_1cuda_1_1FarnebackOpticalFlow.html',1,'cv::cuda::FarnebackOpticalFlow'],['../de/d9e/classcv_1_1FarnebackOpticalFlow.html',1,'cv::FarnebackOpticalFlow']]],
  ['fastbilateralsolverfilter',['FastBilateralSolverFilter',['../db/d50/classcv_1_1ximgproc_1_1FastBilateralSolverFilter.html',1,'cv::ximgproc']]],
  ['fastfeaturedetector',['FastFeatureDetector',['../d4/d6a/classcv_1_1cuda_1_1FastFeatureDetector.html',1,'cv::cuda::FastFeatureDetector'],['../df/d74/classcv_1_1FastFeatureDetector.html',1,'cv::FastFeatureDetector']]],
  ['fastglobalsmootherfilter',['FastGlobalSmootherFilter',['../de/d13/classcv_1_1ximgproc_1_1FastGlobalSmootherFilter.html',1,'cv::ximgproc']]],
  ['fasticpodometry',['FastICPOdometry',['../d9/d63/classcv_1_1rgbd_1_1FastICPOdometry.html',1,'cv::rgbd']]],
  ['fastlinedetector',['FastLineDetector',['../df/d4c/classcv_1_1ximgproc_1_1FastLineDetector.html',1,'cv::ximgproc']]],
  ['fastmarchingmethod',['FastMarchingMethod',['../d3/dea/classcv_1_1videostab_1_1FastMarchingMethod.html',1,'cv::videostab']]],
  ['fastopticalflowbm',['FastOpticalFlowBM',['../df/db2/classcv_1_1cuda_1_1FastOpticalFlowBM.html',1,'cv::cuda']]],
  ['featherblender',['FeatherBlender',['../d4/d69/classcv_1_1detail_1_1FeatherBlender.html',1,'cv::detail']]],
  ['feature',['Feature',['../d9/db9/structcv_1_1linemod_1_1Feature.html',1,'cv::linemod::Feature'],['../d9/de1/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHOGEvaluator_1_1Feature.html',1,'cv::detail::tracking::contrib_feature::CvHOGEvaluator::Feature'],['../d5/d96/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvLBPEvaluator_1_1Feature.html',1,'cv::detail::tracking::contrib_feature::CvLBPEvaluator::Feature']]],
  ['feature2d',['Feature2D',['../d0/d13/classcv_1_1Feature2D.html',1,'cv']]],
  ['feature2dasync',['Feature2DAsync',['../df/db9/classcv_1_1cuda_1_1Feature2DAsync.html',1,'cv::cuda']]],
  ['featurehaar',['FeatureHaar',['../dc/d04/classcv_1_1detail_1_1tracking_1_1contrib__feature_1_1CvHaarEvaluator_1_1FeatureHaar.html',1,'cv::detail::tracking::contrib_feature::CvHaarEvaluator']]],
  ['featuresmatcher',['FeaturesMatcher',['../da/d87/classcv_1_1detail_1_1FeaturesMatcher.html',1,'cv::detail']]],
  ['fgdparams',['FGDParams',['../de/def/structcv_1_1cuda_1_1FGDParams.html',1,'cv::cuda']]],
  ['filenode',['FileNode',['../de/dd9/classcv_1_1FileNode.html',1,'cv']]],
  ['filenodeiterator',['FileNodeIterator',['../d7/d4e/classcv_1_1FileNodeIterator.html',1,'cv']]],
  ['filestorage',['FileStorage',['../da/d56/classcv_1_1FileStorage.html',1,'cv']]],
  ['filter',['Filter',['../dc/d2b/classcv_1_1cuda_1_1Filter.html',1,'cv::cuda']]],
  ['finalshowcaller',['FinalShowCaller',['../d0/da3/classcvv_1_1FinalShowCaller.html',1,'cvv']]],
  ['findmaxvalexprbody',['FindMaxValExprBody',['../d9/d48/structcv_1_1cudev_1_1FindMaxValExprBody.html',1,'cv::cudev']]],
  ['findminmaxvalexprbody',['FindMinMaxValExprBody',['../dd/db3/structcv_1_1cudev_1_1FindMinMaxValExprBody.html',1,'cv::cudev']]],
  ['findminvalexprbody',['FindMinValExprBody',['../df/d82/structcv_1_1cudev_1_1FindMinValExprBody.html',1,'cv::cudev']]],
  ['fisherfacerecognizer',['FisherFaceRecognizer',['../d2/de9/classcv_1_1face_1_1FisherFaceRecognizer.html',1,'cv::face']]],
  ['fisheyeprojector',['FisheyeProjector',['../d9/de9/structcv_1_1detail_1_1FisheyeProjector.html',1,'cv::detail']]],
  ['fisheyewarper',['FisheyeWarper',['../d9/dac/classcv_1_1detail_1_1FisheyeWarper.html',1,'cv::detail::FisheyeWarper'],['../d5/d30/classcv_1_1FisheyeWarper.html',1,'cv::FisheyeWarper']]],
  ['flannbasedmatcher',['FlannBasedMatcher',['../dc/de2/classcv_1_1FlannBasedMatcher.html',1,'cv']]],
  ['flatten_5fg',['flatten_g',['../dd/d3b/structcv_1_1detail_1_1flatten__g.html',1,'cv::detail']]],
  ['flatten_5fg_3c_20cv_3a_3agmat_20_3e',['flatten_g&lt; cv::GMat &gt;',['../df/de8/structcv_1_1detail_1_1flatten__g_3_01cv_1_1GMat_01_4.html',1,'cv::detail']]],
  ['flatten_5fg_3c_20cv_3a_3agscalar_20_3e',['flatten_g&lt; cv::GScalar &gt;',['../d5/d97/structcv_1_1detail_1_1flatten__g_3_01cv_1_1GScalar_01_4.html',1,'cv::detail']]],
  ['flattenlayer',['FlattenLayer',['../d4/da3/classcv_1_1dnn_1_1FlattenLayer.html',1,'cv::dnn']]],
  ['float16_5ft',['float16_t',['../df/dc9/classcv_1_1float16__t.html',1,'cv']]],
  ['floattype',['FloatType',['../d8/d4e/structcv_1_1cudev_1_1functional__detail_1_1FloatType.html',1,'cv::cudev::functional_detail']]],
  ['floorlayer',['FloorLayer',['../d4/d53/classcv_1_1dnn_1_1FloorLayer.html',1,'cv::dnn']]],
  ['flowwarplayer',['FlowWarpLayer',['../db/de2/classcv_1_1dnn_1_1FlowWarpLayer.html',1,'cv::dnn']]],
  ['fluid_5fget_5fin',['fluid_get_in',['../d3/d36/structcv_1_1detail_1_1fluid__get__in.html',1,'cv::detail']]],
  ['fluid_5fget_5fin_3c_20cv_3a_3agarray_3c_20u_20_3e_20_3e',['fluid_get_in&lt; cv::GArray&lt; U &gt; &gt;',['../d1/dde/structcv_1_1detail_1_1fluid__get__in_3_01cv_1_1GArray_3_01U_01_4_01_4.html',1,'cv::detail']]],
  ['fluid_5fget_5fin_3c_20cv_3a_3agmat_20_3e',['fluid_get_in&lt; cv::GMat &gt;',['../dc/dd6/structcv_1_1detail_1_1fluid__get__in_3_01cv_1_1GMat_01_4.html',1,'cv::detail']]],
  ['fluid_5fget_5fin_3c_20cv_3a_3agopaque_3c_20u_20_3e_20_3e',['fluid_get_in&lt; cv::GOpaque&lt; U &gt; &gt;',['../de/d84/structcv_1_1detail_1_1fluid__get__in_3_01cv_1_1GOpaque_3_01U_01_4_01_4.html',1,'cv::detail']]],
  ['fluid_5fget_5fin_3c_20cv_3a_3agscalar_20_3e',['fluid_get_in&lt; cv::GScalar &gt;',['../d8/de3/structcv_1_1detail_1_1fluid__get__in_3_01cv_1_1GScalar_01_4.html',1,'cv::detail']]],
  ['fluidcallhelper',['FluidCallHelper',['../d6/daf/structcv_1_1detail_1_1FluidCallHelper.html',1,'cv::detail']]],
  ['fluidcallhelper_3c_20impl_2c_20std_3a_3atuple_3c_20ins_2e_2e_2e_20_3e_2c_20std_3a_3atuple_3c_20outs_2e_2e_2e_20_3e_2c_20usescratch_20_3e',['FluidCallHelper&lt; Impl, std::tuple&lt; Ins... &gt;, std::tuple&lt; Outs... &gt;, UseScratch &gt;',['../d4/d77/structcv_1_1detail_1_1FluidCallHelper_3_01Impl_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01std_1_16cb3b081e952d44068dce53ded07afdc.html',1,'cv::detail']]],
  ['formatinfo',['FormatInfo',['../d8/db6/structcv_1_1cudacodec_1_1FormatInfo.html',1,'cv::cudacodec']]],
  ['formatted',['Formatted',['../d4/df3/classcv_1_1Formatted.html',1,'cv']]],
  ['formatter',['Formatter',['../d3/da1/classcv_1_1Formatter.html',1,'cv']]],
  ['fpdenormalsignorehintscope',['FPDenormalsIgnoreHintScope',['../d9/d16/classcv_1_1details_1_1FPDenormalsIgnoreHintScope.html',1,'cv::details']]],
  ['fpdenormalsignorehintscopenoop',['FPDenormalsIgnoreHintScopeNOOP',['../db/d57/classcv_1_1details_1_1FPDenormalsIgnoreHintScopeNOOP.html',1,'cv::details']]],
  ['fpdenormalsmodestate',['FPDenormalsModeState',['../df/dfd/structcv_1_1details_1_1FPDenormalsModeState.html',1,'cv::details']]],
  ['fr_5fadience',['FR_adience',['../d2/dff/classcv_1_1datasets_1_1FR__adience.html',1,'cv::datasets']]],
  ['fr_5fadienceobj',['FR_adienceObj',['../d6/deb/structcv_1_1datasets_1_1FR__adienceObj.html',1,'cv::datasets']]],
  ['fr_5flfw',['FR_lfw',['../dd/dda/classcv_1_1datasets_1_1FR__lfw.html',1,'cv::datasets']]],
  ['fr_5flfwobj',['FR_lfwObj',['../d9/d2d/structcv_1_1datasets_1_1FR__lfwObj.html',1,'cv::datasets']]],
  ['framesource',['FrameSource',['../d4/dd6/classcv_1_1superres_1_1FrameSource.html',1,'cv::superres']]],
  ['freak',['FREAK',['../df/db4/classcv_1_1xfeatures2d_1_1FREAK.html',1,'cv::xfeatures2d']]],
  ['freetype2',['FreeType2',['../d9/dfa/classcv_1_1freetype_1_1FreeType2.html',1,'cv::freetype']]],
  ['freetype_5ffont',['freetype_font',['../d6/d08/structcv_1_1gapi_1_1wip_1_1draw_1_1freetype__font.html',1,'cv::gapi::wip::draw']]],
  ['fromfilemotionreader',['FromFileMotionReader',['../d9/db3/classcv_1_1videostab_1_1FromFileMotionReader.html',1,'cv::videostab']]],
  ['ftext',['FText',['../d6/d69/structcv_1_1gapi_1_1wip_1_1draw_1_1FText.html',1,'cv::gapi::wip::draw']]],
  ['function',['Function',['../da/d62/classcv_1_1MinProblemSolver_1_1Function.html',1,'cv::MinProblemSolver']]]
];
