var searchData=
[
  ['radialvariancehash',['RadialVarianceHash',['../d5/d97/classcv_1_1img__hash_1_1RadialVarianceHash.html',1,'cv::img_hash']]],
  ['randompatterncornerfinder',['RandomPatternCornerFinder',['../df/d8d/classcv_1_1randpattern_1_1RandomPatternCornerFinder.html',1,'cv::randpattern']]],
  ['randompatterngenerator',['RandomPatternGenerator',['../d7/d43/classcv_1_1randpattern_1_1RandomPatternGenerator.html',1,'cv::randpattern']]],
  ['range',['Range',['../da/d35/classcv_1_1Range.html',1,'cv']]],
  ['ransacparams',['RansacParams',['../da/dc7/structcv_1_1videostab_1_1RansacParams.html',1,'cv::videostab']]],
  ['rapid',['Rapid',['../d1/d8e/classcv_1_1rapid_1_1Rapid.html',1,'cv::rapid']]],
  ['rawvideosource',['RawVideoSource',['../d6/d55/classcv_1_1cudacodec_1_1RawVideoSource.html',1,'cv::cudacodec']]],
  ['rebind',['rebind',['../da/d52/classcv_1_1Allocator_1_1rebind.html',1,'cv::Allocator&lt; _Tp &gt;::rebind&lt; U &gt;'],['../d1/d1d/structcv_1_1cudev_1_1Sum_1_1rebind.html',1,'cv::cudev::Sum&lt; T &gt;::rebind&lt; U &gt;'],['../d3/dd1/structcv_1_1cudev_1_1Avg_1_1rebind.html',1,'cv::cudev::Avg&lt; T &gt;::rebind&lt; U &gt;'],['../d2/dff/structcv_1_1cudev_1_1Min_1_1rebind.html',1,'cv::cudev::Min&lt; T &gt;::rebind&lt; U &gt;'],['../d1/d7c/structcv_1_1cudev_1_1Max_1_1rebind.html',1,'cv::cudev::Max&lt; T &gt;::rebind&lt; U &gt;']]],
  ['reciprocallayer',['ReciprocalLayer',['../d5/d8e/classcv_1_1dnn_1_1ReciprocalLayer.html',1,'cv::dnn']]],
  ['rect',['Rect',['../d3/d22/classcv_1_1gapi_1_1own_1_1Rect.html',1,'cv::gapi::own::Rect'],['../d6/d30/structcv_1_1gapi_1_1wip_1_1draw_1_1Rect.html',1,'cv::gapi::wip::draw::Rect']]],
  ['rect_5f',['Rect_',['../d2/d44/classcv_1_1Rect__.html',1,'cv']]],
  ['reducelayer',['ReduceLayer',['../df/d26/classcv_1_1dnn_1_1ReduceLayer.html',1,'cv::dnn']]],
  ['reducelayerint8',['ReduceLayerInt8',['../d9/dc1/classcv_1_1dnn_1_1ReduceLayerInt8.html',1,'cv::dnn']]],
  ['reducetocolumnbody',['ReduceToColumnBody',['../d5/df4/structcv_1_1cudev_1_1ReduceToColumnBody.html',1,'cv::cudev']]],
  ['reducetorowbody',['ReduceToRowBody',['../da/d58/structcv_1_1cudev_1_1ReduceToRowBody.html',1,'cv::cudev']]],
  ['regionlayer',['RegionLayer',['../d1/d21/classcv_1_1dnn_1_1RegionLayer.html',1,'cv::dnn']]],
  ['relu6layer',['ReLU6Layer',['../dc/dcd/classcv_1_1dnn_1_1ReLU6Layer.html',1,'cv::dnn']]],
  ['relulayer',['ReLULayer',['../dd/df0/classcv_1_1dnn_1_1ReLULayer.html',1,'cv::dnn']]],
  ['remapptr1',['RemapPtr1',['../dc/d09/structcv_1_1cudev_1_1RemapPtr1.html',1,'cv::cudev']]],
  ['remapptr1sz',['RemapPtr1Sz',['../dd/d03/structcv_1_1cudev_1_1RemapPtr1Sz.html',1,'cv::cudev']]],
  ['remapptr2',['RemapPtr2',['../d1/d32/structcv_1_1cudev_1_1RemapPtr2.html',1,'cv::cudev']]],
  ['remapptr2sz',['RemapPtr2Sz',['../d4/d59/structcv_1_1cudev_1_1RemapPtr2Sz.html',1,'cv::cudev']]],
  ['reorglayer',['ReorgLayer',['../d6/da3/classcv_1_1dnn_1_1ReorgLayer.html',1,'cv::dnn']]],
  ['reprojector',['Reprojector',['../d3/def/structcv_1_1kinfu_1_1Intr_1_1Reprojector.html',1,'cv::kinfu::Intr']]],
  ['requantizelayer',['RequantizeLayer',['../da/d2c/classcv_1_1dnn_1_1RequantizeLayer.html',1,'cv::dnn']]],
  ['reshapelayer',['ReshapeLayer',['../db/d15/classcv_1_1dnn_1_1ReshapeLayer.html',1,'cv::dnn']]],
  ['resizedimagedescriptor',['ResizedImageDescriptor',['../dc/d5a/classcv_1_1detail_1_1tracking_1_1tbm_1_1ResizedImageDescriptor.html',1,'cv::detail::tracking::tbm']]],
  ['resizelayer',['ResizeLayer',['../db/d38/classcv_1_1dnn_1_1ResizeLayer.html',1,'cv::dnn']]],
  ['resizeptr',['ResizePtr',['../d5/db1/structcv_1_1cudev_1_1ResizePtr.html',1,'cv::cudev']]],
  ['resizeptrsz',['ResizePtrSz',['../d3/d8a/structcv_1_1cudev_1_1ResizePtrSz.html',1,'cv::cudev']]],
  ['retina',['Retina',['../dc/d54/classcv_1_1bioinspired_1_1Retina.html',1,'cv::bioinspired']]],
  ['retinafasttonemapping',['RetinaFastToneMapping',['../dd/d73/classcv_1_1bioinspired_1_1RetinaFastToneMapping.html',1,'cv::bioinspired']]],
  ['retinaparameters',['RetinaParameters',['../d2/df5/structcv_1_1bioinspired_1_1RetinaParameters.html',1,'cv::bioinspired']]],
  ['rffeaturegetter',['RFFeatureGetter',['../dc/dca/classcv_1_1ximgproc_1_1RFFeatureGetter.html',1,'cv::ximgproc']]],
  ['rgb2gray',['RGB2Gray',['../d9/d5f/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Gray.html',1,'']]],
  ['rgb2hls',['RGB2HLS',['../de/d2b/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2HLS.html',1,'']]],
  ['rgb2hsv',['RGB2HSV',['../de/d72/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2HSV.html',1,'']]],
  ['rgb2lab',['RGB2Lab',['../db/df2/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Lab.html',1,'']]],
  ['rgb2luv',['RGB2Luv',['../d0/d2c/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2Luv.html',1,'']]],
  ['rgb2rgb',['RGB2RGB',['../de/d9d/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2RGB.html',1,'']]],
  ['rgb2xyz',['RGB2XYZ',['../d1/ddf/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2XYZ.html',1,'']]],
  ['rgb2ycrcb',['RGB2YCrCb',['../da/d08/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2YCrCb.html',1,'']]],
  ['rgb2yuv',['RGB2YUV',['../d6/d96/classcv_1_1cudev_1_1color__cvt__detail_1_1RGB2YUV.html',1,'']]],
  ['rgb_5fto_5fgray_5ffunc',['RGB_to_GRAY_func',['../d8/ded/structcv_1_1cudev_1_1RGB__to__GRAY__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffull_5ffunc',['RGB_to_HLS4_FULL_func',['../d2/d93/structcv_1_1cudev_1_1RGB__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HLS4_FULL_func&lt; float &gt;',['../db/deb/structcv_1_1cudev_1_1RGB__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffunc',['RGB_to_HLS4_func',['../d9/d77/structcv_1_1cudev_1_1RGB__to__HLS4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls4_5ffunc_3c_20float_20_3e',['RGB_to_HLS4_func&lt; float &gt;',['../d6/d6b/structcv_1_1cudev_1_1RGB__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffull_5ffunc',['RGB_to_HLS_FULL_func',['../d5/d13/structcv_1_1cudev_1_1RGB__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HLS_FULL_func&lt; float &gt;',['../d1/d6f/structcv_1_1cudev_1_1RGB__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffunc',['RGB_to_HLS_func',['../d8/d24/structcv_1_1cudev_1_1RGB__to__HLS__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhls_5ffunc_3c_20float_20_3e',['RGB_to_HLS_func&lt; float &gt;',['../d8/d04/structcv_1_1cudev_1_1RGB__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffull_5ffunc',['RGB_to_HSV4_FULL_func',['../dc/d3a/structcv_1_1cudev_1_1RGB__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HSV4_FULL_func&lt; float &gt;',['../d5/d76/structcv_1_1cudev_1_1RGB__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffunc',['RGB_to_HSV4_func',['../d8/db1/structcv_1_1cudev_1_1RGB__to__HSV4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['RGB_to_HSV4_func&lt; float &gt;',['../d9/da5/structcv_1_1cudev_1_1RGB__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffull_5ffunc',['RGB_to_HSV_FULL_func',['../da/dee/structcv_1_1cudev_1_1RGB__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['RGB_to_HSV_FULL_func&lt; float &gt;',['../d0/d0e/structcv_1_1cudev_1_1RGB__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffunc',['RGB_to_HSV_func',['../db/d4e/structcv_1_1cudev_1_1RGB__to__HSV__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fhsv_5ffunc_3c_20float_20_3e',['RGB_to_HSV_func&lt; float &gt;',['../db/d37/structcv_1_1cudev_1_1RGB__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgb_5fto_5flab4_5ffunc',['RGB_to_Lab4_func',['../d2/d21/structcv_1_1cudev_1_1RGB__to__Lab4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5flab_5ffunc',['RGB_to_Lab_func',['../db/d41/structcv_1_1cudev_1_1RGB__to__Lab__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fluv4_5ffunc',['RGB_to_Luv4_func',['../d5/d72/structcv_1_1cudev_1_1RGB__to__Luv4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fluv_5ffunc',['RGB_to_Luv_func',['../dc/db6/structcv_1_1cudev_1_1RGB__to__Luv__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fxyz4_5ffunc',['RGB_to_XYZ4_func',['../d2/dd8/structcv_1_1cudev_1_1RGB__to__XYZ4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fxyz_5ffunc',['RGB_to_XYZ_func',['../dd/d54/structcv_1_1cudev_1_1RGB__to__XYZ__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fycrcb4_5ffunc',['RGB_to_YCrCb4_func',['../df/d11/structcv_1_1cudev_1_1RGB__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fycrcb_5ffunc',['RGB_to_YCrCb_func',['../df/d9a/structcv_1_1cudev_1_1RGB__to__YCrCb__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fyuv4_5ffunc',['RGB_to_YUV4_func',['../d9/d7a/structcv_1_1cudev_1_1RGB__to__YUV4__func.html',1,'cv::cudev']]],
  ['rgb_5fto_5fyuv_5ffunc',['RGB_to_YUV_func',['../d7/d9f/structcv_1_1cudev_1_1RGB__to__YUV__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fgray_5ffunc',['RGBA_to_GRAY_func',['../db/d04/structcv_1_1cudev_1_1RGBA__to__GRAY__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffull_5ffunc',['RGBA_to_HLS4_FULL_func',['../d0/d56/structcv_1_1cudev_1_1RGBA__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HLS4_FULL_func&lt; float &gt;',['../de/d5e/structcv_1_1cudev_1_1RGBA__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffunc',['RGBA_to_HLS4_func',['../d6/d31/structcv_1_1cudev_1_1RGBA__to__HLS4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls4_5ffunc_3c_20float_20_3e',['RGBA_to_HLS4_func&lt; float &gt;',['../d8/dcb/structcv_1_1cudev_1_1RGBA__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffull_5ffunc',['RGBA_to_HLS_FULL_func',['../dd/db8/structcv_1_1cudev_1_1RGBA__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HLS_FULL_func&lt; float &gt;',['../d4/dd3/structcv_1_1cudev_1_1RGBA__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffunc',['RGBA_to_HLS_func',['../d9/dd5/structcv_1_1cudev_1_1RGBA__to__HLS__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhls_5ffunc_3c_20float_20_3e',['RGBA_to_HLS_func&lt; float &gt;',['../d2/d0c/structcv_1_1cudev_1_1RGBA__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffull_5ffunc',['RGBA_to_HSV4_FULL_func',['../dd/d19/structcv_1_1cudev_1_1RGBA__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HSV4_FULL_func&lt; float &gt;',['../d1/d1f/structcv_1_1cudev_1_1RGBA__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffunc',['RGBA_to_HSV4_func',['../d7/d25/structcv_1_1cudev_1_1RGBA__to__HSV4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['RGBA_to_HSV4_func&lt; float &gt;',['../db/d05/structcv_1_1cudev_1_1RGBA__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffull_5ffunc',['RGBA_to_HSV_FULL_func',['../db/d47/structcv_1_1cudev_1_1RGBA__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['RGBA_to_HSV_FULL_func&lt; float &gt;',['../d0/d1c/structcv_1_1cudev_1_1RGBA__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffunc',['RGBA_to_HSV_func',['../d1/d7d/structcv_1_1cudev_1_1RGBA__to__HSV__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fhsv_5ffunc_3c_20float_20_3e',['RGBA_to_HSV_func&lt; float &gt;',['../d0/d9b/structcv_1_1cudev_1_1RGBA__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['rgba_5fto_5flab4_5ffunc',['RGBA_to_Lab4_func',['../df/d38/structcv_1_1cudev_1_1RGBA__to__Lab4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5flab_5ffunc',['RGBA_to_Lab_func',['../d2/d37/structcv_1_1cudev_1_1RGBA__to__Lab__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fluv4_5ffunc',['RGBA_to_Luv4_func',['../d7/d2e/structcv_1_1cudev_1_1RGBA__to__Luv4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fluv_5ffunc',['RGBA_to_Luv_func',['../de/d88/structcv_1_1cudev_1_1RGBA__to__Luv__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fxyz4_5ffunc',['RGBA_to_XYZ4_func',['../d9/da9/structcv_1_1cudev_1_1RGBA__to__XYZ4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fxyz_5ffunc',['RGBA_to_XYZ_func',['../d7/d53/structcv_1_1cudev_1_1RGBA__to__XYZ__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fycrcb4_5ffunc',['RGBA_to_YCrCb4_func',['../d0/dd4/structcv_1_1cudev_1_1RGBA__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fycrcb_5ffunc',['RGBA_to_YCrCb_func',['../d1/dd1/structcv_1_1cudev_1_1RGBA__to__YCrCb__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fyuv4_5ffunc',['RGBA_to_YUV4_func',['../d3/da0/structcv_1_1cudev_1_1RGBA__to__YUV4__func.html',1,'cv::cudev']]],
  ['rgba_5fto_5fyuv_5ffunc',['RGBA_to_YUV_func',['../db/d21/structcv_1_1cudev_1_1RGBA__to__YUV__func.html',1,'cv::cudev']]],
  ['rgbdframe',['RgbdFrame',['../d3/d9c/structcv_1_1rgbd_1_1RgbdFrame.html',1,'cv::rgbd']]],
  ['rgbdicpodometry',['RgbdICPOdometry',['../d2/d0f/classcv_1_1rgbd_1_1RgbdICPOdometry.html',1,'cv::rgbd']]],
  ['rgbdnormals',['RgbdNormals',['../d1/d5b/classcv_1_1rgbd_1_1RgbdNormals.html',1,'cv::rgbd']]],
  ['rgbdodometry',['RgbdOdometry',['../d0/d60/classcv_1_1rgbd_1_1RgbdOdometry.html',1,'cv::rgbd']]],
  ['rgbdplane',['RgbdPlane',['../d6/d50/classcv_1_1rgbd_1_1RgbdPlane.html',1,'cv::rgbd']]],
  ['ricinterpolator',['RICInterpolator',['../d2/da4/classcv_1_1ximgproc_1_1RICInterpolator.html',1,'cv::ximgproc']]],
  ['ridgedetectionfilter',['RidgeDetectionFilter',['../d4/d36/classcv_1_1ximgproc_1_1RidgeDetectionFilter.html',1,'cv::ximgproc']]],
  ['rlofopticalflowparameter',['RLOFOpticalFlowParameter',['../d4/d91/classcv_1_1optflow_1_1RLOFOpticalFlowParameter.html',1,'cv::optflow']]],
  ['rmat',['RMat',['../d0/d46/classcv_1_1RMat.html',1,'cv']]],
  ['rng',['RNG',['../d1/dd6/classcv_1_1RNG.html',1,'cv']]],
  ['rng_5fmt19937',['RNG_MT19937',['../db/d3e/classcv_1_1RNG__MT19937.html',1,'cv']]],
  ['rnnlayer',['RNNLayer',['../dd/dfd/classcv_1_1dnn_1_1RNNLayer.html',1,'cv::dnn']]],
  ['rotatedrect',['RotatedRect',['../db/dd6/classcv_1_1RotatedRect.html',1,'cv']]],
  ['rotationwarper',['RotationWarper',['../da/db8/classcv_1_1detail_1_1RotationWarper.html',1,'cv::detail']]],
  ['rotationwarperbase',['RotationWarperBase',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearportraitprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20compressedrectilinearprojector_20_3e',['RotationWarperBase&lt; CompressedRectilinearProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalportraitprojector_20_3e',['RotationWarperBase&lt; CylindricalPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20cylindricalprojector_20_3e',['RotationWarperBase&lt; CylindricalProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20fisheyeprojector_20_3e',['RotationWarperBase&lt; FisheyeProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20mercatorprojector_20_3e',['RotationWarperBase&lt; MercatorProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniportraitprojector_20_3e',['RotationWarperBase&lt; PaniniPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20paniniprojector_20_3e',['RotationWarperBase&lt; PaniniProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeportraitprojector_20_3e',['RotationWarperBase&lt; PlanePortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20planeprojector_20_3e',['RotationWarperBase&lt; PlaneProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalportraitprojector_20_3e',['RotationWarperBase&lt; SphericalPortraitProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20sphericalprojector_20_3e',['RotationWarperBase&lt; SphericalProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20stereographicprojector_20_3e',['RotationWarperBase&lt; StereographicProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['rotationwarperbase_3c_20transversemercatorprojector_20_3e',['RotationWarperBase&lt; TransverseMercatorProjector &gt;',['../d6/d65/classcv_1_1detail_1_1RotationWarperBase.html',1,'cv::detail']]],
  ['roundlayer',['RoundLayer',['../de/da0/classcv_1_1dnn_1_1RoundLayer.html',1,'cv::dnn']]],
  ['rtrees',['RTrees',['../d0/d65/classcv_1_1ml_1_1RTrees.html',1,'cv::ml']]]
];
