var searchData=
[
  ['backendnode',['BackendNode',['../d2/dbb/classcv_1_1dnn_1_1BackendNode.html',1,'cv::dnn']]],
  ['backendwrapper',['BackendWrapper',['../df/d7b/classcv_1_1dnn_1_1BackendWrapper.html',1,'cv::dnn']]],
  ['backgroundsubtractor',['BackgroundSubtractor',['../d7/df6/classcv_1_1BackgroundSubtractor.html',1,'cv']]],
  ['backgroundsubtractorcnt',['BackgroundSubtractorCNT',['../de/dca/classcv_1_1bgsegm_1_1BackgroundSubtractorCNT.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorfgd',['BackgroundSubtractorFGD',['../d3/dd2/classcv_1_1cuda_1_1BackgroundSubtractorFGD.html',1,'cv::cuda']]],
  ['backgroundsubtractorgmg',['BackgroundSubtractorGMG',['../d1/d5c/classcv_1_1bgsegm_1_1BackgroundSubtractorGMG.html',1,'cv::bgsegm::BackgroundSubtractorGMG'],['../d5/df2/classcv_1_1cuda_1_1BackgroundSubtractorGMG.html',1,'cv::cuda::BackgroundSubtractorGMG']]],
  ['backgroundsubtractorgsoc',['BackgroundSubtractorGSOC',['../d4/dd5/classcv_1_1bgsegm_1_1BackgroundSubtractorGSOC.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorknn',['BackgroundSubtractorKNN',['../db/d88/classcv_1_1BackgroundSubtractorKNN.html',1,'cv']]],
  ['backgroundsubtractorlsbp',['BackgroundSubtractorLSBP',['../de/d4c/classcv_1_1bgsegm_1_1BackgroundSubtractorLSBP.html',1,'cv::bgsegm']]],
  ['backgroundsubtractorlsbpdesc',['BackgroundSubtractorLSBPDesc',['../d1/de5/classcv_1_1bgsegm_1_1BackgroundSubtractorLSBPDesc.html',1,'cv::bgsegm']]],
  ['backgroundsubtractormog',['BackgroundSubtractorMOG',['../d6/da7/classcv_1_1bgsegm_1_1BackgroundSubtractorMOG.html',1,'cv::bgsegm::BackgroundSubtractorMOG'],['../d1/dfe/classcv_1_1cuda_1_1BackgroundSubtractorMOG.html',1,'cv::cuda::BackgroundSubtractorMOG']]],
  ['backgroundsubtractormog2',['BackgroundSubtractorMOG2',['../df/d23/classcv_1_1cuda_1_1BackgroundSubtractorMOG2.html',1,'cv::cuda::BackgroundSubtractorMOG2'],['../d7/d7b/classcv_1_1BackgroundSubtractorMOG2.html',1,'cv::BackgroundSubtractorMOG2']]],
  ['backgroundsubtractorparams',['BackgroundSubtractorParams',['../d4/d7d/structcv_1_1gapi_1_1video_1_1BackgroundSubtractorParams.html',1,'cv::gapi::video']]],
  ['bad_5fany_5fcast',['bad_any_cast',['../dc/d1b/classcv_1_1util_1_1bad__any__cast.html',1,'cv::util']]],
  ['bad_5foptional_5faccess',['bad_optional_access',['../dd/dd6/classcv_1_1util_1_1bad__optional__access.html',1,'cv::util']]],
  ['bad_5fvariant_5faccess',['bad_variant_access',['../d1/d54/classcv_1_1util_1_1bad__variant__access.html',1,'cv::util']]],
  ['barcodedetector',['BarcodeDetector',['../dc/df7/classcv_1_1barcode_1_1BarcodeDetector.html',1,'cv::barcode']]],
  ['basecascadeclassifier',['BaseCascadeClassifier',['../da/dd5/classcv_1_1BaseCascadeClassifier.html',1,'cv']]],
  ['baseclassifier',['BaseClassifier',['../d7/d49/classcv_1_1detail_1_1tracking_1_1online__boosting_1_1BaseClassifier.html',1,'cv::detail::tracking::online_boosting']]],
  ['baseconvolutionlayer',['BaseConvolutionLayer',['../d5/d1f/classcv_1_1dnn_1_1BaseConvolutionLayer.html',1,'cv::dnn']]],
  ['baseocr',['BaseOCR',['../de/d3a/classcv_1_1text_1_1BaseOCR.html',1,'cv::text']]],
  ['basesfm',['BaseSFM',['../d7/db1/classcv_1_1sfm_1_1BaseSFM.html',1,'cv::sfm']]],
  ['basicfacerecognizer',['BasicFaceRecognizer',['../dc/dd7/classcv_1_1face_1_1BasicFaceRecognizer.html',1,'cv::face']]],
  ['basicopaqueref',['BasicOpaqueRef',['../d0/d1d/classcv_1_1detail_1_1BasicOpaqueRef.html',1,'cv::detail']]],
  ['basicvectorref',['BasicVectorRef',['../df/d63/classcv_1_1detail_1_1BasicVectorRef.html',1,'cv::detail']]],
  ['batchnormlayer',['BatchNormLayer',['../d4/dd2/classcv_1_1dnn_1_1BatchNormLayer.html',1,'cv::dnn']]],
  ['batchnormlayerint8',['BatchNormLayerInt8',['../d8/dbc/classcv_1_1dnn_1_1BatchNormLayerInt8.html',1,'cv::dnn']]],
  ['bbox',['BBox',['../db/d18/classcv_1_1face_1_1FacemarkLBF_1_1BBox.html',1,'cv::face::FacemarkLBF']]],
  ['beblid',['BEBLID',['../d7/d99/classcv_1_1xfeatures2d_1_1BEBLID.html',1,'cv::xfeatures2d']]],
  ['bestof2nearestmatcher',['BestOf2NearestMatcher',['../d4/d26/classcv_1_1detail_1_1BestOf2NearestMatcher.html',1,'cv::detail']]],
  ['bestof2nearestrangematcher',['BestOf2NearestRangeMatcher',['../d8/d72/classcv_1_1detail_1_1BestOf2NearestRangeMatcher.html',1,'cv::detail']]],
  ['bfmatcher',['BFMatcher',['../d3/da1/classcv_1_1BFMatcher.html',1,'cv']]],
  ['bgr_5fto_5fbgra_5ffunc',['BGR_to_BGRA_func',['../d2/def/structcv_1_1cudev_1_1BGR__to__BGRA__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fgray_5ffunc',['BGR_to_GRAY_func',['../d1/d6e/structcv_1_1cudev_1_1BGR__to__GRAY__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffull_5ffunc',['BGR_to_HLS4_FULL_func',['../d5/d9d/structcv_1_1cudev_1_1BGR__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HLS4_FULL_func&lt; float &gt;',['../dd/d95/structcv_1_1cudev_1_1BGR__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffunc',['BGR_to_HLS4_func',['../d1/d99/structcv_1_1cudev_1_1BGR__to__HLS4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls4_5ffunc_3c_20float_20_3e',['BGR_to_HLS4_func&lt; float &gt;',['../d5/dfd/structcv_1_1cudev_1_1BGR__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffull_5ffunc',['BGR_to_HLS_FULL_func',['../de/d50/structcv_1_1cudev_1_1BGR__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HLS_FULL_func&lt; float &gt;',['../d7/db4/structcv_1_1cudev_1_1BGR__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffunc',['BGR_to_HLS_func',['../d7/d28/structcv_1_1cudev_1_1BGR__to__HLS__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhls_5ffunc_3c_20float_20_3e',['BGR_to_HLS_func&lt; float &gt;',['../db/d58/structcv_1_1cudev_1_1BGR__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffull_5ffunc',['BGR_to_HSV4_FULL_func',['../de/d04/structcv_1_1cudev_1_1BGR__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HSV4_FULL_func&lt; float &gt;',['../d1/d5e/structcv_1_1cudev_1_1BGR__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffunc',['BGR_to_HSV4_func',['../d9/db2/structcv_1_1cudev_1_1BGR__to__HSV4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['BGR_to_HSV4_func&lt; float &gt;',['../d7/dc2/structcv_1_1cudev_1_1BGR__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffull_5ffunc',['BGR_to_HSV_FULL_func',['../d5/d12/structcv_1_1cudev_1_1BGR__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['BGR_to_HSV_FULL_func&lt; float &gt;',['../dd/d00/structcv_1_1cudev_1_1BGR__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffunc',['BGR_to_HSV_func',['../dd/d23/structcv_1_1cudev_1_1BGR__to__HSV__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fhsv_5ffunc_3c_20float_20_3e',['BGR_to_HSV_func&lt; float &gt;',['../d6/df7/structcv_1_1cudev_1_1BGR__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgr_5fto_5flab4_5ffunc',['BGR_to_Lab4_func',['../d9/df2/structcv_1_1cudev_1_1BGR__to__Lab4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5flab_5ffunc',['BGR_to_Lab_func',['../d5/d91/structcv_1_1cudev_1_1BGR__to__Lab__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fluv4_5ffunc',['BGR_to_Luv4_func',['../de/d8b/structcv_1_1cudev_1_1BGR__to__Luv4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fluv_5ffunc',['BGR_to_Luv_func',['../da/d92/structcv_1_1cudev_1_1BGR__to__Luv__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5frgb_5ffunc',['BGR_to_RGB_func',['../df/dd8/structcv_1_1cudev_1_1BGR__to__RGB__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5frgba_5ffunc',['BGR_to_RGBA_func',['../d8/d77/structcv_1_1cudev_1_1BGR__to__RGBA__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fxyz4_5ffunc',['BGR_to_XYZ4_func',['../d7/d78/structcv_1_1cudev_1_1BGR__to__XYZ4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fxyz_5ffunc',['BGR_to_XYZ_func',['../d1/d61/structcv_1_1cudev_1_1BGR__to__XYZ__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fycrcb4_5ffunc',['BGR_to_YCrCb4_func',['../d3/d27/structcv_1_1cudev_1_1BGR__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fycrcb_5ffunc',['BGR_to_YCrCb_func',['../d5/d3a/structcv_1_1cudev_1_1BGR__to__YCrCb__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fyuv4_5ffunc',['BGR_to_YUV4_func',['../db/d18/structcv_1_1cudev_1_1BGR__to__YUV4__func.html',1,'cv::cudev']]],
  ['bgr_5fto_5fyuv_5ffunc',['BGR_to_YUV_func',['../d7/d5d/structcv_1_1cudev_1_1BGR__to__YUV__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fbgr_5ffunc',['BGRA_to_BGR_func',['../d6/d66/structcv_1_1cudev_1_1BGRA__to__BGR__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fgray_5ffunc',['BGRA_to_GRAY_func',['../de/d7e/structcv_1_1cudev_1_1BGRA__to__GRAY__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffull_5ffunc',['BGRA_to_HLS4_FULL_func',['../d8/d7c/structcv_1_1cudev_1_1BGRA__to__HLS4__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HLS4_FULL_func&lt; float &gt;',['../dd/d9f/structcv_1_1cudev_1_1BGRA__to__HLS4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffunc',['BGRA_to_HLS4_func',['../dc/da3/structcv_1_1cudev_1_1BGRA__to__HLS4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls4_5ffunc_3c_20float_20_3e',['BGRA_to_HLS4_func&lt; float &gt;',['../d2/d33/structcv_1_1cudev_1_1BGRA__to__HLS4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffull_5ffunc',['BGRA_to_HLS_FULL_func',['../d9/ddf/structcv_1_1cudev_1_1BGRA__to__HLS__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HLS_FULL_func&lt; float &gt;',['../d0/d64/structcv_1_1cudev_1_1BGRA__to__HLS__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffunc',['BGRA_to_HLS_func',['../de/d08/structcv_1_1cudev_1_1BGRA__to__HLS__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhls_5ffunc_3c_20float_20_3e',['BGRA_to_HLS_func&lt; float &gt;',['../d8/d90/structcv_1_1cudev_1_1BGRA__to__HLS__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffull_5ffunc',['BGRA_to_HSV4_FULL_func',['../d6/da1/structcv_1_1cudev_1_1BGRA__to__HSV4__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HSV4_FULL_func&lt; float &gt;',['../d4/df0/structcv_1_1cudev_1_1BGRA__to__HSV4__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffunc',['BGRA_to_HSV4_func',['../d0/d82/structcv_1_1cudev_1_1BGRA__to__HSV4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv4_5ffunc_3c_20float_20_3e',['BGRA_to_HSV4_func&lt; float &gt;',['../d3/d25/structcv_1_1cudev_1_1BGRA__to__HSV4__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffull_5ffunc',['BGRA_to_HSV_FULL_func',['../db/d15/structcv_1_1cudev_1_1BGRA__to__HSV__FULL__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffull_5ffunc_3c_20float_20_3e',['BGRA_to_HSV_FULL_func&lt; float &gt;',['../d3/d43/structcv_1_1cudev_1_1BGRA__to__HSV__FULL__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffunc',['BGRA_to_HSV_func',['../dc/d1f/structcv_1_1cudev_1_1BGRA__to__HSV__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fhsv_5ffunc_3c_20float_20_3e',['BGRA_to_HSV_func&lt; float &gt;',['../d9/d8a/structcv_1_1cudev_1_1BGRA__to__HSV__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['bgra_5fto_5flab4_5ffunc',['BGRA_to_Lab4_func',['../d0/de7/structcv_1_1cudev_1_1BGRA__to__Lab4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5flab_5ffunc',['BGRA_to_Lab_func',['../d4/d7d/structcv_1_1cudev_1_1BGRA__to__Lab__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fluv4_5ffunc',['BGRA_to_Luv4_func',['../de/d52/structcv_1_1cudev_1_1BGRA__to__Luv4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fluv_5ffunc',['BGRA_to_Luv_func',['../de/d8c/structcv_1_1cudev_1_1BGRA__to__Luv__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5frgb_5ffunc',['BGRA_to_RGB_func',['../d4/de2/structcv_1_1cudev_1_1BGRA__to__RGB__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5frgba_5ffunc',['BGRA_to_RGBA_func',['../d4/ddf/structcv_1_1cudev_1_1BGRA__to__RGBA__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fxyz4_5ffunc',['BGRA_to_XYZ4_func',['../d8/d57/structcv_1_1cudev_1_1BGRA__to__XYZ4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fxyz_5ffunc',['BGRA_to_XYZ_func',['../de/d69/structcv_1_1cudev_1_1BGRA__to__XYZ__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fycrcb4_5ffunc',['BGRA_to_YCrCb4_func',['../d3/d09/structcv_1_1cudev_1_1BGRA__to__YCrCb4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fycrcb_5ffunc',['BGRA_to_YCrCb_func',['../d6/dbd/structcv_1_1cudev_1_1BGRA__to__YCrCb__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fyuv4_5ffunc',['BGRA_to_YUV4_func',['../db/d43/structcv_1_1cudev_1_1BGRA__to__YUV4__func.html',1,'cv::cudev']]],
  ['bgra_5fto_5fyuv_5ffunc',['BGRA_to_YUV_func',['../db/d7e/structcv_1_1cudev_1_1BGRA__to__YUV__func.html',1,'cv::cudev']]],
  ['bif',['BIF',['../dc/d12/classcv_1_1face_1_1BIF.html',1,'cv::face']]],
  ['binary_5ffunction',['binary_function',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20double_2c_20double_2c_20double_20_3e',['binary_function&lt; double, double, double &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20float_2c_20float_2c_20float_20_3e',['binary_function&lt; float, float, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20int_2c_20int_2c_20float_20_3e',['binary_function&lt; int, int, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20int_2c_20int_2c_20int_20_3e',['binary_function&lt; int, int, int &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20predicate_3a_3afirst_5fargument_5ftype_2c_20predicate_3a_3asecond_5fargument_5ftype_2c_20predicate_3a_3aresult_5ftype_20_3e',['binary_function&lt; Predicate::first_argument_type, Predicate::second_argument_type, Predicate::result_type &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20schar_2c_20schar_2c_20float_20_3e',['binary_function&lt; schar, schar, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20schar_2c_20schar_2c_20schar_20_3e',['binary_function&lt; schar, schar, schar &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20short_2c_20short_2c_20float_20_3e',['binary_function&lt; short, short, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20short_2c_20short_2c_20short_20_3e',['binary_function&lt; short, short, short &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t_2c_20float_2c_20float_20_3e',['binary_function&lt; T, float, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20functional_5fdetail_3a_3afloattype_3c_20t_20_3e_3a_3atype_20_3e',['binary_function&lt; T, T, functional_detail::FloatType&lt; T &gt;::type &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20makevec_3c_20uchar_2c_20vectraits_3c_20t_20_3e_3a_3acn_20_3e_3a_3atype_20_3e',['binary_function&lt; T, T, MakeVec&lt; uchar, VecTraits&lt; T &gt;::cn &gt;::type &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t_2c_20t_2c_20t_20_3e',['binary_function&lt; T, T, T &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t1_20_3e',['binary_function&lt; T1, T2, T1 &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20t1_2c_20t2_2c_20t2_20_3e',['binary_function&lt; T1, T2, T2 &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20uchar_2c_20uchar_2c_20float_20_3e',['binary_function&lt; uchar, uchar, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20uchar_2c_20uchar_2c_20uchar_20_3e',['binary_function&lt; uchar, uchar, uchar &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20uint_2c_20uint_2c_20float_20_3e',['binary_function&lt; uint, uint, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20uint_2c_20uint_2c_20uint_20_3e',['binary_function&lt; uint, uint, uint &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20ushort_2c_20ushort_2c_20float_20_3e',['binary_function&lt; ushort, ushort, float &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binary_5ffunction_3c_20ushort_2c_20ushort_2c_20ushort_20_3e',['binary_function&lt; ushort, ushort, ushort &gt;',['../d6/ddf/structcv_1_1cudev_1_1binary__function.html',1,'cv::cudev']]],
  ['binarydescriptor',['BinaryDescriptor',['../d6/d83/classcv_1_1line__descriptor_1_1BinaryDescriptor.html',1,'cv::line_descriptor']]],
  ['binarydescriptormatcher',['BinaryDescriptorMatcher',['../d2/dde/classcv_1_1line__descriptor_1_1BinaryDescriptorMatcher.html',1,'cv::line_descriptor']]],
  ['binarynegate',['BinaryNegate',['../d1/d81/structcv_1_1cudev_1_1BinaryNegate.html',1,'cv::cudev']]],
  ['binarytransformptr',['BinaryTransformPtr',['../db/d77/structcv_1_1cudev_1_1BinaryTransformPtr.html',1,'cv::cudev']]],
  ['binarytransformptrsz',['BinaryTransformPtrSz',['../d1/d0a/structcv_1_1cudev_1_1BinaryTransformPtrSz.html',1,'cv::cudev']]],
  ['binarytupleadapter',['BinaryTupleAdapter',['../dc/da3/structcv_1_1cudev_1_1BinaryTupleAdapter.html',1,'cv::cudev']]],
  ['binder1st',['Binder1st',['../d5/dee/structcv_1_1cudev_1_1Binder1st.html',1,'cv::cudev']]],
  ['binder2nd',['Binder2nd',['../d6/db4/structcv_1_1cudev_1_1Binder2nd.html',1,'cv::cudev']]],
  ['bit_5fand',['bit_and',['../d9/de7/structcv_1_1cudev_1_1bit__and.html',1,'cv::cudev']]],
  ['bit_5flshift',['bit_lshift',['../d3/d65/structcv_1_1cudev_1_1bit__lshift.html',1,'cv::cudev']]],
  ['bit_5fnot',['bit_not',['../d0/d8a/structcv_1_1cudev_1_1bit__not.html',1,'cv::cudev']]],
  ['bit_5for',['bit_or',['../dd/d1c/structcv_1_1cudev_1_1bit__or.html',1,'cv::cudev']]],
  ['bit_5frshift',['bit_rshift',['../d4/d2a/structcv_1_1cudev_1_1bit__rshift.html',1,'cv::cudev']]],
  ['bit_5fxor',['bit_xor',['../df/d44/structcv_1_1cudev_1_1bit__xor.html',1,'cv::cudev']]],
  ['blanklayer',['BlankLayer',['../d8/d2d/classcv_1_1dnn_1_1BlankLayer.html',1,'cv::dnn']]],
  ['blender',['Blender',['../d6/d4a/classcv_1_1detail_1_1Blender.html',1,'cv::detail']]],
  ['block',['Block',['../d3/d6c/structcv_1_1cudev_1_1Block.html',1,'cv::cudev']]],
  ['blockmeanhash',['BlockMeanHash',['../df/d55/classcv_1_1img__hash_1_1BlockMeanHash.html',1,'cv::img_hash']]],
  ['blockschannelscompensator',['BlocksChannelsCompensator',['../d3/dab/classcv_1_1detail_1_1BlocksChannelsCompensator.html',1,'cv::detail']]],
  ['blockscompensator',['BlocksCompensator',['../da/df4/classcv_1_1detail_1_1BlocksCompensator.html',1,'cv::detail']]],
  ['blocksgaincompensator',['BlocksGainCompensator',['../d7/d81/classcv_1_1detail_1_1BlocksGainCompensator.html',1,'cv::detail']]],
  ['bnlllayer',['BNLLLayer',['../d0/d87/classcv_1_1dnn_1_1BNLLLayer.html',1,'cv::dnn']]],
  ['board',['Board',['../d4/db2/classcv_1_1aruco_1_1Board.html',1,'cv::aruco']]],
  ['boost',['Boost',['../d6/d7a/classcv_1_1ml_1_1Boost.html',1,'cv::ml']]],
  ['boostdesc',['BoostDesc',['../d1/dfd/classcv_1_1xfeatures2d_1_1BoostDesc.html',1,'cv::xfeatures2d']]],
  ['border',['Border',['../db/deb/structcv_1_1gapi_1_1fluid_1_1Border.html',1,'cv::gapi::fluid']]],
  ['bowimgdescriptorextractor',['BOWImgDescriptorExtractor',['../d2/d6b/classcv_1_1BOWImgDescriptorExtractor.html',1,'cv']]],
  ['bowkmeanstrainer',['BOWKMeansTrainer',['../d4/d72/classcv_1_1BOWKMeansTrainer.html',1,'cv']]],
  ['bowtrainer',['BOWTrainer',['../d5/d14/classcv_1_1BOWTrainer.html',1,'cv']]],
  ['box',['Box',['../d7/d59/structcv_1_1ximgproc_1_1Box.html',1,'cv::ximgproc']]],
  ['brdbase',['BrdBase',['../de/d53/structcv_1_1cudev_1_1BrdBase.html',1,'cv::cudev']]],
  ['brdconstant',['BrdConstant',['../da/dfa/structcv_1_1cudev_1_1BrdConstant.html',1,'cv::cudev']]],
  ['brdreflect',['BrdReflect',['../dc/dff/structcv_1_1cudev_1_1BrdReflect.html',1,'cv::cudev']]],
  ['brdreflect101',['BrdReflect101',['../d3/d12/structcv_1_1cudev_1_1BrdReflect101.html',1,'cv::cudev']]],
  ['brdreplicate',['BrdReplicate',['../d7/de8/structcv_1_1cudev_1_1BrdReplicate.html',1,'cv::cudev']]],
  ['brdwrap',['BrdWrap',['../da/d69/structcv_1_1cudev_1_1BrdWrap.html',1,'cv::cudev']]],
  ['briefdescriptorextractor',['BriefDescriptorExtractor',['../d1/d93/classcv_1_1xfeatures2d_1_1BriefDescriptorExtractor.html',1,'cv::xfeatures2d']]],
  ['brisk',['BRISK',['../de/dbf/classcv_1_1BRISK.html',1,'cv']]],
  ['broxopticalflow',['BroxOpticalFlow',['../dc/dd1/classcv_1_1superres_1_1BroxOpticalFlow.html',1,'cv::superres::BroxOpticalFlow'],['../d7/d18/classcv_1_1cuda_1_1BroxOpticalFlow.html',1,'cv::cuda::BroxOpticalFlow']]],
  ['buffer',['Buffer',['../dc/d92/classcv_1_1gapi_1_1fluid_1_1Buffer.html',1,'cv::gapi::fluid::Buffer'],['../d3/d68/classcv_1_1ogl_1_1Buffer.html',1,'cv::ogl::Buffer']]],
  ['bufferarea',['BufferArea',['../d8/d2e/classcv_1_1utils_1_1BufferArea.html',1,'cv::utils']]],
  ['bufferpool',['BufferPool',['../d5/d08/classcv_1_1cuda_1_1BufferPool.html',1,'cv::cuda']]],
  ['bufferpoolcontroller',['BufferPoolController',['../d4/dad/classcv_1_1BufferPoolController.html',1,'cv']]],
  ['bundleadjusteraffine',['BundleAdjusterAffine',['../d6/d8d/classcv_1_1detail_1_1BundleAdjusterAffine.html',1,'cv::detail']]],
  ['bundleadjusteraffinepartial',['BundleAdjusterAffinePartial',['../d4/dbb/classcv_1_1detail_1_1BundleAdjusterAffinePartial.html',1,'cv::detail']]],
  ['bundleadjusterbase',['BundleAdjusterBase',['../d5/d56/classcv_1_1detail_1_1BundleAdjusterBase.html',1,'cv::detail']]],
  ['bundleadjusterray',['BundleAdjusterRay',['../da/d7c/classcv_1_1detail_1_1BundleAdjusterRay.html',1,'cv::detail']]],
  ['bundleadjusterreproj',['BundleAdjusterReproj',['../dc/d54/classcv_1_1detail_1_1BundleAdjusterReproj.html',1,'cv::detail']]]
];
