var searchData=
[
  ['tag',['tag',['../d3/d02/structcv_1_1datasets_1_1tag.html',1,'cv::datasets']]],
  ['tan_5ffunc',['tan_func',['../d7/d3e/structcv_1_1cudev_1_1tan__func.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20double_20_3e',['tan_func&lt; double &gt;',['../db/dc4/structcv_1_1cudev_1_1tan__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20float_20_3e',['tan_func&lt; float &gt;',['../d5/d4e/structcv_1_1cudev_1_1tan__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20schar_20_3e',['tan_func&lt; schar &gt;',['../d7/d9d/structcv_1_1cudev_1_1tan__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20short_20_3e',['tan_func&lt; short &gt;',['../d6/dbd/structcv_1_1cudev_1_1tan__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uchar_20_3e',['tan_func&lt; uchar &gt;',['../d2/d0d/structcv_1_1cudev_1_1tan__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20uint_20_3e',['tan_func&lt; uint &gt;',['../d6/d9e/structcv_1_1cudev_1_1tan__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tan_5ffunc_3c_20ushort_20_3e',['tan_func&lt; ushort &gt;',['../d2/d63/structcv_1_1cudev_1_1tan__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc',['tanh_func',['../d5/d7b/structcv_1_1cudev_1_1tanh__func.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20double_20_3e',['tanh_func&lt; double &gt;',['../d4/d9f/structcv_1_1cudev_1_1tanh__func_3_01double_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20float_20_3e',['tanh_func&lt; float &gt;',['../dc/da0/structcv_1_1cudev_1_1tanh__func_3_01float_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20schar_20_3e',['tanh_func&lt; schar &gt;',['../d5/dfc/structcv_1_1cudev_1_1tanh__func_3_01schar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20short_20_3e',['tanh_func&lt; short &gt;',['../d8/db4/structcv_1_1cudev_1_1tanh__func_3_01short_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uchar_20_3e',['tanh_func&lt; uchar &gt;',['../d8/d5a/structcv_1_1cudev_1_1tanh__func_3_01uchar_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20uint_20_3e',['tanh_func&lt; uint &gt;',['../df/dc6/structcv_1_1cudev_1_1tanh__func_3_01uint_01_4.html',1,'cv::cudev']]],
  ['tanh_5ffunc_3c_20ushort_20_3e',['tanh_func&lt; ushort &gt;',['../d6/d68/structcv_1_1cudev_1_1tanh__func_3_01ushort_01_4.html',1,'cv::cudev']]],
  ['tanhlayer',['TanHLayer',['../df/d66/classcv_1_1dnn_1_1TanHLayer.html',1,'cv::dnn']]],
  ['tanlayer',['TanLayer',['../d9/d1e/classcv_1_1dnn_1_1TanLayer.html',1,'cv::dnn']]],
  ['targetarchs',['TargetArchs',['../d9/dee/classcv_1_1cuda_1_1TargetArchs.html',1,'cv::cuda']]],
  ['tbmr',['TBMR',['../de/de2/classcv_1_1xfeatures2d_1_1TBMR.html',1,'cv::xfeatures2d']]],
  ['template',['Template',['../d2/dc7/structcv_1_1linemod_1_1Template.html',1,'cv::linemod']]],
  ['templatematching',['TemplateMatching',['../d2/d58/classcv_1_1cuda_1_1TemplateMatching.html',1,'cv::cuda']]],
  ['termcriteria',['TermCriteria',['../d9/d5d/classcv_1_1TermCriteria.html',1,'cv']]],
  ['text',['Text',['../d6/d0f/structcv_1_1gapi_1_1wip_1_1draw_1_1Text.html',1,'cv::gapi::wip::draw']]],
  ['textdetectionmodel',['TextDetectionModel',['../d4/de1/classcv_1_1dnn_1_1TextDetectionModel.html',1,'cv::dnn']]],
  ['textdetectionmodel_5fdb',['TextDetectionModel_DB',['../db/d0f/classcv_1_1dnn_1_1TextDetectionModel__DB.html',1,'cv::dnn']]],
  ['textdetectionmodel_5feast',['TextDetectionModel_EAST',['../d8/ddc/classcv_1_1dnn_1_1TextDetectionModel__EAST.html',1,'cv::dnn']]],
  ['textdetector',['TextDetector',['../de/d25/classcv_1_1text_1_1TextDetector.html',1,'cv::text']]],
  ['textdetectorcnn',['TextDetectorCNN',['../d1/d66/classcv_1_1text_1_1TextDetectorCNN.html',1,'cv::text']]],
  ['textrecognitionmodel',['TextRecognitionModel',['../de/dee/classcv_1_1dnn_1_1TextRecognitionModel.html',1,'cv::dnn']]],
  ['texture',['Texture',['../db/d26/structcv_1_1face_1_1FacemarkAAM_1_1Model_1_1Texture.html',1,'cv::face::FacemarkAAM::Model::Texture'],['../d0/dc5/structcv_1_1cudev_1_1Texture.html',1,'cv::cudev::Texture&lt; T &gt;']]],
  ['texture2d',['Texture2D',['../d5/ddf/classcv_1_1ogl_1_1Texture2D.html',1,'cv::ogl']]],
  ['textureptr',['TexturePtr',['../d2/d09/structcv_1_1cudev_1_1TexturePtr.html',1,'cv::cudev']]],
  ['thash',['THash',['../da/dff/structTHash.html',1,'']]],
  ['thinplatesplineshapetransformer',['ThinPlateSplineShapeTransformer',['../dc/d18/classcv_1_1ThinPlateSplineShapeTransformer.html',1,'cv']]],
  ['threshbinaryfunc',['ThreshBinaryFunc',['../df/df5/structcv_1_1cudev_1_1ThreshBinaryFunc.html',1,'cv::cudev']]],
  ['threshbinaryinvfunc',['ThreshBinaryInvFunc',['../da/d5e/structcv_1_1cudev_1_1ThreshBinaryInvFunc.html',1,'cv::cudev']]],
  ['thresholdedrelulayer',['ThresholdedReluLayer',['../d5/d51/classcv_1_1dnn_1_1ThresholdedReluLayer.html',1,'cv::dnn']]],
  ['threshtozerofunc',['ThreshToZeroFunc',['../df/dd9/structcv_1_1cudev_1_1ThreshToZeroFunc.html',1,'cv::cudev']]],
  ['threshtozeroinvfunc',['ThreshToZeroInvFunc',['../d8/d7e/structcv_1_1cudev_1_1ThreshToZeroInvFunc.html',1,'cv::cudev']]],
  ['threshtruncfunc',['ThreshTruncFunc',['../d0/d44/structcv_1_1cudev_1_1ThreshTruncFunc.html',1,'cv::cudev']]],
  ['tickmeter',['TickMeter',['../d9/d6f/classcv_1_1TickMeter.html',1,'cv']]],
  ['timelapser',['Timelapser',['../dd/dac/classcv_1_1detail_1_1Timelapser.html',1,'cv::detail']]],
  ['timelapsercrop',['TimelapserCrop',['../df/db9/classcv_1_1detail_1_1TimelapserCrop.html',1,'cv::detail']]],
  ['timer',['Timer',['../df/d4a/classcv_1_1ocl_1_1Timer.html',1,'cv::ocl']]],
  ['tlsdata',['TLSData',['../d9/db0/classcv_1_1TLSData.html',1,'cv']]],
  ['tlsdata_3c_20cv_3a_3ainstr_3a_3anodedatatls_20_3e',['TLSData&lt; cv::instr::NodeDataTls &gt;',['../d9/db0/classcv_1_1TLSData.html',1,'cv']]],
  ['tlsdataaccumulator',['TLSDataAccumulator',['../dc/d6e/classcv_1_1TLSDataAccumulator.html',1,'cv']]],
  ['tlsdataaccumulator_3c_20cv_3a_3ainstr_3a_3anodedatatls_20_3e',['TLSDataAccumulator&lt; cv::instr::NodeDataTls &gt;',['../dc/d6e/classcv_1_1TLSDataAccumulator.html',1,'cv']]],
  ['tlsdatacontainer',['TLSDataContainer',['../df/d21/classcv_1_1TLSDataContainer.html',1,'cv']]],
  ['tofilemotionwriter',['ToFileMotionWriter',['../dc/dc1/classcv_1_1videostab_1_1ToFileMotionWriter.html',1,'cv::videostab']]],
  ['tonemap',['Tonemap',['../d8/d5e/classcv_1_1Tonemap.html',1,'cv']]],
  ['tonemapdrago',['TonemapDrago',['../da/d53/classcv_1_1TonemapDrago.html',1,'cv']]],
  ['tonemapdurand',['TonemapDurand',['../d1/db3/classcv_1_1xphoto_1_1TonemapDurand.html',1,'cv::xphoto']]],
  ['tonemapmantiuk',['TonemapMantiuk',['../de/d76/classcv_1_1TonemapMantiuk.html',1,'cv']]],
  ['tonemapreinhard',['TonemapReinhard',['../d0/dec/classcv_1_1TonemapReinhard.html',1,'cv']]],
  ['tr_5fchars',['TR_chars',['../d7/dc3/classcv_1_1datasets_1_1TR__chars.html',1,'cv::datasets']]],
  ['tr_5fcharsobj',['TR_charsObj',['../d8/d14/structcv_1_1datasets_1_1TR__charsObj.html',1,'cv::datasets']]],
  ['tr_5ficdar',['TR_icdar',['../d7/dfb/classcv_1_1datasets_1_1TR__icdar.html',1,'cv::datasets']]],
  ['tr_5ficdarobj',['TR_icdarObj',['../de/d04/structcv_1_1datasets_1_1TR__icdarObj.html',1,'cv::datasets']]],
  ['tr_5fsvt',['TR_svt',['../da/dc9/classcv_1_1datasets_1_1TR__svt.html',1,'cv::datasets']]],
  ['tr_5fsvtobj',['TR_svtObj',['../d3/dc5/structcv_1_1datasets_1_1TR__svtObj.html',1,'cv::datasets']]],
  ['track',['Track',['../d7/d20/classcv_1_1detail_1_1tracking_1_1tbm_1_1Track.html',1,'cv::detail::tracking::tbm']]],
  ['track_5falov',['TRACK_alov',['../d8/d1c/classcv_1_1datasets_1_1TRACK__alov.html',1,'cv::datasets']]],
  ['track_5falovobj',['TRACK_alovObj',['../dd/d88/structcv_1_1datasets_1_1TRACK__alovObj.html',1,'cv::datasets']]],
  ['track_5fvot',['TRACK_vot',['../dc/d52/classcv_1_1datasets_1_1TRACK__vot.html',1,'cv::datasets']]],
  ['track_5fvotobj',['TRACK_votObj',['../d9/d36/structcv_1_1datasets_1_1TRACK__votObj.html',1,'cv::datasets']]],
  ['tracked_5fcv_5fmat',['tracked_cv_mat',['../d3/d73/structcv_1_1detail_1_1tracked__cv__mat.html',1,'cv::detail']]],
  ['tracked_5fcv_5fumat',['tracked_cv_umat',['../d1/df4/structcv_1_1detail_1_1tracked__cv__umat.html',1,'cv::detail']]],
  ['trackedobject',['TrackedObject',['../da/d5a/structcv_1_1detail_1_1tracking_1_1tbm_1_1TrackedObject.html',1,'cv::detail::tracking::tbm::TrackedObject'],['../dc/de0/structcv_1_1DetectionBasedTracker_1_1TrackedObject.html',1,'cv::DetectionBasedTracker::TrackedObject']]],
  ['tracker',['Tracker',['../dc/d48/classcv_1_1rapid_1_1Tracker.html',1,'cv::rapid::Tracker'],['../d0/d0a/classcv_1_1Tracker.html',1,'cv::Tracker'],['../db/dfe/classcv_1_1legacy_1_1Tracker.html',1,'cv::legacy::Tracker']]],
  ['trackeradaboostingtargetstate',['TrackerAdaBoostingTargetState',['../d9/d33/classcv_1_1detail_1_1tracking_1_1TrackerStateEstimatorAdaBoosting_1_1TrackerAdaBoostingTargetState.html',1,'cv::detail::tracking::TrackerStateEstimatorAdaBoosting']]],
  ['trackerboosting',['TrackerBoosting',['../db/df1/classcv_1_1legacy_1_1TrackerBoosting.html',1,'cv::legacy']]],
  ['trackercontribfeature',['TrackerContribFeature',['../d5/d1b/classcv_1_1detail_1_1tracking_1_1TrackerContribFeature.html',1,'cv::detail::tracking']]],
  ['trackercontribfeaturehaar',['TrackerContribFeatureHAAR',['../d0/d82/classcv_1_1detail_1_1tracking_1_1TrackerContribFeatureHAAR.html',1,'cv::detail::tracking']]],
  ['trackercontribfeatureset',['TrackerContribFeatureSet',['../dd/d4e/classcv_1_1detail_1_1tracking_1_1TrackerContribFeatureSet.html',1,'cv::detail::tracking']]],
  ['trackercontribsampler',['TrackerContribSampler',['../dc/dd7/classcv_1_1detail_1_1tracking_1_1TrackerContribSampler.html',1,'cv::detail::tracking']]],
  ['trackercontribsampleralgorithm',['TrackerContribSamplerAlgorithm',['../dc/d27/classcv_1_1detail_1_1tracking_1_1TrackerContribSamplerAlgorithm.html',1,'cv::detail::tracking']]],
  ['trackercontribsamplercsc',['TrackerContribSamplerCSC',['../db/d5e/classcv_1_1detail_1_1tracking_1_1TrackerContribSamplerCSC.html',1,'cv::detail::tracking']]],
  ['trackercsrt',['TrackerCSRT',['../d2/da2/classcv_1_1TrackerCSRT.html',1,'cv::TrackerCSRT'],['../d7/d8f/classcv_1_1legacy_1_1TrackerCSRT.html',1,'cv::legacy::TrackerCSRT']]],
  ['trackerdasiamrpn',['TrackerDaSiamRPN',['../de/d93/classcv_1_1TrackerDaSiamRPN.html',1,'cv']]],
  ['trackerfeature',['TrackerFeature',['../d9/d84/classcv_1_1detail_1_1tracking_1_1TrackerFeature.html',1,'cv::detail::tracking']]],
  ['trackerfeaturefeature2d',['TrackerFeatureFeature2d',['../d7/d24/classcv_1_1detail_1_1tracking_1_1TrackerFeatureFeature2d.html',1,'cv::detail::tracking']]],
  ['trackerfeaturehog',['TrackerFeatureHOG',['../d0/d64/classcv_1_1detail_1_1tracking_1_1TrackerFeatureHOG.html',1,'cv::detail::tracking']]],
  ['trackerfeaturelbp',['TrackerFeatureLBP',['../d9/d77/classcv_1_1detail_1_1tracking_1_1TrackerFeatureLBP.html',1,'cv::detail::tracking']]],
  ['trackerfeatureset',['TrackerFeatureSet',['../df/da4/classcv_1_1detail_1_1tracking_1_1TrackerFeatureSet.html',1,'cv::detail::tracking']]],
  ['trackergoturn',['TrackerGOTURN',['../d7/d4c/classcv_1_1TrackerGOTURN.html',1,'cv']]],
  ['trackerkcf',['TrackerKCF',['../d5/d6a/classcv_1_1legacy_1_1TrackerKCF.html',1,'cv::legacy::TrackerKCF'],['../d2/dff/classcv_1_1TrackerKCF.html',1,'cv::TrackerKCF']]],
  ['trackermedianflow',['TrackerMedianFlow',['../dd/d94/classcv_1_1legacy_1_1TrackerMedianFlow.html',1,'cv::legacy']]],
  ['trackermil',['TrackerMIL',['../d9/dbc/classcv_1_1legacy_1_1TrackerMIL.html',1,'cv::legacy::TrackerMIL'],['../d0/d26/classcv_1_1TrackerMIL.html',1,'cv::TrackerMIL']]],
  ['trackermodel',['TrackerModel',['../da/dba/classcv_1_1detail_1_1tracking_1_1TrackerModel.html',1,'cv::detail::tracking']]],
  ['trackermosse',['TrackerMOSSE',['../d0/d20/classcv_1_1legacy_1_1TrackerMOSSE.html',1,'cv::legacy']]],
  ['trackerparams',['TrackerParams',['../d7/d92/structcv_1_1detail_1_1tracking_1_1tbm_1_1TrackerParams.html',1,'cv::detail::tracking::tbm']]],
  ['trackersampler',['TrackerSampler',['../dc/d24/classcv_1_1detail_1_1tracking_1_1TrackerSampler.html',1,'cv::detail::tracking']]],
  ['trackersampleralgorithm',['TrackerSamplerAlgorithm',['../de/d0a/classcv_1_1detail_1_1tracking_1_1TrackerSamplerAlgorithm.html',1,'cv::detail::tracking']]],
  ['trackersamplercs',['TrackerSamplerCS',['../d0/d58/classcv_1_1detail_1_1tracking_1_1TrackerSamplerCS.html',1,'cv::detail::tracking']]],
  ['trackersamplercsc',['TrackerSamplerCSC',['../da/d59/classcv_1_1detail_1_1tracking_1_1TrackerSamplerCSC.html',1,'cv::detail::tracking']]],
  ['trackersamplerpf',['TrackerSamplerPF',['../d5/d35/classcv_1_1detail_1_1tracking_1_1TrackerSamplerPF.html',1,'cv::detail::tracking']]],
  ['trackerstateestimator',['TrackerStateEstimator',['../d8/dd0/classcv_1_1detail_1_1tracking_1_1TrackerStateEstimator.html',1,'cv::detail::tracking']]],
  ['trackerstateestimatoradaboosting',['TrackerStateEstimatorAdaBoosting',['../d5/d10/classcv_1_1detail_1_1tracking_1_1TrackerStateEstimatorAdaBoosting.html',1,'cv::detail::tracking']]],
  ['trackerstateestimatorsvm',['TrackerStateEstimatorSVM',['../d2/d6e/classcv_1_1detail_1_1tracking_1_1TrackerStateEstimatorSVM.html',1,'cv::detail::tracking']]],
  ['trackertargetstate',['TrackerTargetState',['../da/d1b/classcv_1_1detail_1_1tracking_1_1TrackerTargetState.html',1,'cv::detail::tracking']]],
  ['trackertld',['TrackerTLD',['../d1/da6/classcv_1_1legacy_1_1TrackerTLD.html',1,'cv::legacy']]],
  ['traindata',['TrainData',['../dc/d32/classcv_1_1ml_1_1TrainData.html',1,'cv::ml']]],
  ['transformtag',['TransformTag',['../d8/d13/structcv_1_1detail_1_1TransformTag.html',1,'cv::detail']]],
  ['transhelper',['TransHelper',['../d7/df5/structcv_1_1detail_1_1TransHelper.html',1,'cv::detail']]],
  ['transhelper_3c_20k_2c_20std_3a_3atuple_3c_20args_2e_2e_2e_20_3e_2c_20r_20_3e',['TransHelper&lt; K, std::tuple&lt; Args... &gt;, R &gt;',['../d7/df5/structcv_1_1detail_1_1TransHelper.html',1,'cv::detail']]],
  ['transhelper_3c_20k_2c_20std_3a_3atuple_3c_20ins_2e_2e_2e_20_3e_2c_20out_20_3e',['TransHelper&lt; K, std::tuple&lt; Ins... &gt;, Out &gt;',['../d5/dd6/structcv_1_1detail_1_1TransHelper_3_01K_00_01std_1_1tuple_3_01Ins_8_8_8_01_4_00_01Out_01_4.html',1,'cv::detail']]],
  ['transientareassegmentationmodule',['TransientAreasSegmentationModule',['../da/d6e/classcv_1_1bioinspired_1_1TransientAreasSegmentationModule.html',1,'cv::bioinspired']]],
  ['translationbasedlocaloutlierrejector',['TranslationBasedLocalOutlierRejector',['../dd/d13/classcv_1_1videostab_1_1TranslationBasedLocalOutlierRejector.html',1,'cv::videostab']]],
  ['transposebody',['TransposeBody',['../d2/d40/structcv_1_1cudev_1_1TransposeBody.html',1,'cv::cudev']]],
  ['transversemercatorprojector',['TransverseMercatorProjector',['../d5/df7/structcv_1_1detail_1_1TransverseMercatorProjector.html',1,'cv::detail']]],
  ['transversemercatorwarper',['TransverseMercatorWarper',['../df/d33/classcv_1_1TransverseMercatorWarper.html',1,'cv::TransverseMercatorWarper'],['../d4/d6b/classcv_1_1detail_1_1TransverseMercatorWarper.html',1,'cv::detail::TransverseMercatorWarper']]],
  ['tupletraits',['TupleTraits',['../dd/d08/structcv_1_1cudev_1_1TupleTraits.html',1,'cv::cudev']]],
  ['tupletraits_3c_20tuple_3c_20p0_2c_20p1_2c_20p2_2c_20p3_2c_20p4_2c_20p5_2c_20p6_2c_20p7_2c_20p8_2c_20p9_20_3e_20_3e',['TupleTraits&lt; tuple&lt; P0, P1, P2, P3, P4, P5, P6, P7, P8, P9 &gt; &gt;',['../d2/dae/structcv_1_1cudev_1_1TupleTraits_3_01tuple_3_01P0_00_01P1_00_01P2_00_01P3_00_01P4_00_01P5_00_01P41642a2d25b95a5ddb87ca2004b28336.html',1,'cv::cudev']]],
  ['twopassstabilizer',['TwoPassStabilizer',['../d8/d9c/classcv_1_1videostab_1_1TwoPassStabilizer.html',1,'cv::videostab']]],
  ['type_5flist_5felement',['type_list_element',['../db/d51/structcv_1_1util_1_1type__list__element.html',1,'cv::util']]],
  ['type_5flist_5findex',['type_list_index',['../d4/d46/structcv_1_1util_1_1type__list__index.html',1,'cv::util']]],
  ['type_5flist_5findex_5fhelper',['type_list_index_helper',['../d1/d34/structcv_1_1util_1_1detail_1_1type__list__index__helper.html',1,'cv::util::detail']]],
  ['type_5flist_5findex_5fhelper_3c_20i_2c_20target_2c_20first_20_3e',['type_list_index_helper&lt; I, Target, First &gt;',['../df/dfa/structcv_1_1util_1_1detail_1_1type__list__index__helper_3_01I_00_01Target_00_01First_01_4.html',1,'cv::util::detail']]],
  ['typehint',['TypeHint',['../df/dc2/structcv_1_1detail_1_1TypeHint.html',1,'cv::detail']]],
  ['typehintbase',['TypeHintBase',['../d6/de4/structcv_1_1detail_1_1TypeHintBase.html',1,'cv::detail']]],
  ['typesequals',['TypesEquals',['../df/d71/structcv_1_1cudev_1_1TypesEquals.html',1,'cv::cudev']]],
  ['typesequals_3c_20a_2c_20a_20_3e',['TypesEquals&lt; A, A &gt;',['../df/dbf/structcv_1_1cudev_1_1TypesEquals_3_01A_00_01A_01_4.html',1,'cv::cudev']]],
  ['typetraits',['TypeTraits',['../d7/d97/structcv_1_1cudev_1_1TypeTraits.html',1,'cv::cudev']]]
];
