var searchData=
[
  ['back_5fprojection_2emarkdown',['back_projection.markdown',['../d5/dbb/back__projection_8markdown.html',1,'']]],
  ['background_5fsegm_2ehpp',['background_segm.hpp',['../db/d73/background__segm_8hpp.html',1,'']]],
  ['background_5fsubtraction_2emarkdown',['background_subtraction.markdown',['../d1/d6d/background__subtraction_8markdown.html',1,'']]],
  ['barcode_2ehpp',['barcode.hpp',['../d5/de9/barcode_8hpp.html',1,'']]],
  ['barcode_5fdetect_5fand_5fdecode_2emarkdown',['barcode_detect_and_decode.markdown',['../d5/d0c/barcode__detect__and__decode_8markdown.html',1,'']]],
  ['base_2ehpp',['base.hpp',['../df/dc3/core_2include_2opencv2_2core_2base_8hpp.html',1,'(Global Namespace)'],['../d7/d29/gapi_2include_2opencv2_2gapi_2s11n_2base_8hpp.html',1,'(Global Namespace)']]],
  ['basic_5fchart_5fdetection_2emarkdown',['basic_chart_detection.markdown',['../db/dc1/basic__chart__detection_8markdown.html',1,'']]],
  ['basic_5fgeometric_5fdrawing_2emarkdown',['basic_geometric_drawing.markdown',['../d8/d61/basic__geometric__drawing_8markdown.html',1,'']]],
  ['basic_5flinear_5ftransform_2emarkdown',['basic_linear_transform.markdown',['../dc/d16/basic__linear__transform_8markdown.html',1,'']]],
  ['bgsegm_2ehpp',['bgsegm.hpp',['../d2/dce/bgsegm_8hpp.html',1,'']]],
  ['bgsegm_5fbg_5fsubtraction_2emarkdown',['bgsegm_bg_subtraction.markdown',['../d3/ddf/bgsegm__bg__subtraction_8markdown.html',1,'']]],
  ['bif_2ehpp',['bif.hpp',['../d3/db4/bif_8hpp.html',1,'']]],
  ['binary_5ffunc_2ehpp',['binary_func.hpp',['../d3/d3c/binary__func_8hpp.html',1,'']]],
  ['binary_5fop_2ehpp',['binary_op.hpp',['../d7/d8d/binary__op_8hpp.html',1,'']]],
  ['bindings_2ehpp',['bindings.hpp',['../d9/d50/bindings_8hpp.html',1,'']]],
  ['bindings_5fie_2ehpp',['bindings_ie.hpp',['../d5/d51/bindings__ie_8hpp.html',1,'']]],
  ['bindings_5futils_2ehpp',['bindings_utils.hpp',['../de/d78/bindings__utils_8hpp.html',1,'']]],
  ['bioinspired_2ehpp',['bioinspired.hpp',['../d4/d64/bioinspired_2bioinspired_8hpp.html',1,'(Global Namespace)'],['../d2/dfa/bioinspired_8hpp.html',1,'(Global Namespace)']]],
  ['blenders_2ehpp',['blenders.hpp',['../d9/d88/blenders_8hpp.html',1,'']]],
  ['block_2ehpp',['block.hpp',['../d3/d30/modules_2core_2include_2opencv2_2core_2cuda_2block_8hpp.html',1,'(Global Namespace)'],['../d4/db0/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2block_8hpp.html',1,'(Global Namespace)']]],
  ['block_5fmean_5fhash_2ehpp',['block_mean_hash.hpp',['../d8/d87/block__mean__hash_8hpp.html',1,'']]],
  ['bm3d_5fimage_5fdenoising_2ehpp',['bm3d_image_denoising.hpp',['../dd/dd5/bm3d__image__denoising_8hpp.html',1,'']]],
  ['border_5finterpolate_2ehpp',['border_interpolate.hpp',['../d5/dd1/border__interpolate_8hpp.html',1,'']]],
  ['bounding_5frects_5fcircles_2emarkdown',['bounding_rects_circles.markdown',['../d9/d5b/bounding__rects__circles_8markdown.html',1,'']]],
  ['bounding_5frotated_5fellipses_2emarkdown',['bounding_rotated_ellipses.markdown',['../dd/d8b/bounding__rotated__ellipses_8markdown.html',1,'']]],
  ['brightedges_2ehpp',['brightedges.hpp',['../d8/dc5/brightedges_8hpp.html',1,'']]],
  ['buffer_5farea_2eprivate_2ehpp',['buffer_area.private.hpp',['../dc/d4a/buffer__area_8private_8hpp.html',1,'']]],
  ['bufferpool_2ehpp',['bufferpool.hpp',['../df/d28/bufferpool_8hpp.html',1,'']]],
  ['building_5ftegra_5fcuda_2emarkdown',['building_tegra_cuda.markdown',['../d7/d04/building__tegra__cuda_8markdown.html',1,'']]]
];
