var searchData=
[
  ['radial_5fvariance_5fhash_2ehpp',['radial_variance_hash.hpp',['../d2/d76/radial__variance__hash_8hpp.html',1,'']]],
  ['radon_5ftransform_2ehpp',['radon_transform.hpp',['../d5/d89/radon__transform_8hpp.html',1,'']]],
  ['random_2eh',['random.h',['../d1/d79/random_8h.html',1,'']]],
  ['random_5fgenerator_5fand_5ftext_2emarkdown',['random_generator_and_text.markdown',['../d7/d1c/random__generator__and__text_8markdown.html',1,'']]],
  ['randpattern_2ehpp',['randpattern.hpp',['../de/dc5/randpattern_8hpp.html',1,'']]],
  ['rapid_2ehpp',['rapid.hpp',['../dd/d04/rapid_8hpp.html',1,'']]],
  ['raster_5fio_5fgdal_2emarkdown',['raster_io_gdal.markdown',['../d5/d67/raster__io__gdal_8markdown.html',1,'']]],
  ['read_5fwrite_5fattributes_2emarkdown',['read_write_attributes.markdown',['../d9/d65/read__write__attributes_8markdown.html',1,'']]],
  ['readme_2emd',['README.md',['../da/ddd/README_8md.html',1,'']]],
  ['real_5ftime_5fpose_2emarkdown',['real_time_pose.markdown',['../dc/d83/real__time__pose_8markdown.html',1,'']]],
  ['reconstruct_2ehpp',['reconstruct.hpp',['../d3/de1/reconstruct_8hpp.html',1,'']]],
  ['reduce_2ehpp',['reduce.hpp',['../da/dca/modules_2core_2include_2opencv2_2core_2cuda_2detail_2reduce_8hpp.html',1,'(Global Namespace)'],['../d3/d78/modules_2core_2include_2opencv2_2core_2cuda_2reduce_8hpp.html',1,'(Global Namespace)'],['../d3/d33/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2reduce_8hpp.html',1,'(Global Namespace)'],['../d4/d25/contrib_2modules_2cudev_2include_2opencv2_2cudev_2grid_2reduce_8hpp.html',1,'(Global Namespace)'],['../d7/da3/contrib_2modules_2cudev_2include_2opencv2_2cudev_2warp_2reduce_8hpp.html',1,'(Global Namespace)']]],
  ['reduce_5fkey_5fval_2ehpp',['reduce_key_val.hpp',['../d3/dbd/reduce__key__val_8hpp.html',1,'']]],
  ['reduce_5fto_5fvec_2ehpp',['reduce_to_vec.hpp',['../d3/ddc/reduce__to__vec_8hpp.html',1,'']]],
  ['reduction_2ehpp',['reduction.hpp',['../d2/da5/reduction_8hpp.html',1,'']]],
  ['registry_2ehpp',['registry.hpp',['../d1/da2/registry_8hpp.html',1,'']]],
  ['remap_2ehpp',['remap.hpp',['../d1/d59/remap_8hpp.html',1,'']]],
  ['remap_2emarkdown',['remap.markdown',['../df/ded/remap_8markdown.html',1,'']]],
  ['render_2ehpp',['render.hpp',['../d1/dda/render_2render_8hpp.html',1,'(Global Namespace)'],['../d6/d4b/render_8hpp.html',1,'(Global Namespace)']]],
  ['render_5ftypes_2ehpp',['render_types.hpp',['../d1/d70/render__types_8hpp.html',1,'']]],
  ['resize_2ehpp',['resize.hpp',['../dc/d12/resize_8hpp.html',1,'']]],
  ['result_5fset_2eh',['result_set.h',['../da/d34/result__set_8h.html',1,'']]],
  ['retina_2ehpp',['retina.hpp',['../d5/d40/retina_8hpp.html',1,'']]],
  ['retina_2emarkdown',['retina.markdown',['../d7/d67/retina_8markdown.html',1,'']]],
  ['retina_5fillusion_2emarkdown',['retina_illusion.markdown',['../d7/d13/retina__illusion_8markdown.html',1,'']]],
  ['retina_5fmodel_2emarkdown',['retina_model.markdown',['../d2/d95/retina__model_8markdown.html',1,'']]],
  ['retinafasttonemapping_2ehpp',['retinafasttonemapping.hpp',['../d2/da3/retinafasttonemapping_8hpp.html',1,'']]],
  ['rgbd_2ehpp',['rgbd.hpp',['../dd/dd3/rgbd_8hpp.html',1,'']]],
  ['ridgefilter_2ehpp',['ridgefilter.hpp',['../d6/df2/ridgefilter_8hpp.html',1,'']]],
  ['ring_5fbuffer_2ehpp',['ring_buffer.hpp',['../d3/dcf/ring__buffer_8hpp.html',1,'']]],
  ['rlofflow_2ehpp',['rlofflow.hpp',['../da/da2/rlofflow_8hpp.html',1,'']]],
  ['rmat_2ehpp',['rmat.hpp',['../d9/d6b/rmat_8hpp.html',1,'']]],
  ['robust_2ehpp',['robust.hpp',['../da/d0b/robust_8hpp.html',1,'']]],
  ['root_2emarkdown',['root.markdown',['../d9/d1d/root_8markdown.html',1,'']]],
  ['run_5flength_5fmorphology_2ehpp',['run_length_morphology.hpp',['../d2/d17/run__length__morphology_8hpp.html',1,'']]]
];
