var searchData=
[
  ['data_5fprovider_5finterface_2ehpp',['data_provider_interface.hpp',['../d4/d60/data__provider__interface_8hpp.html',1,'']]],
  ['datamov_5futils_2ehpp',['datamov_utils.hpp',['../df/dcf/datamov__utils_8hpp.html',1,'']]],
  ['dataset_2ehpp',['dataset.hpp',['../dc/d6a/dataset_8hpp.html',1,'']]],
  ['dct_5fimage_5fdenoising_2ehpp',['dct_image_denoising.hpp',['../da/dd8/dct__image__denoising_8hpp.html',1,'']]],
  ['deblurring_2ehpp',['deblurring.hpp',['../d4/db5/deblurring_8hpp.html',1,'']]],
  ['debug_5fmode_2ehpp',['debug_mode.hpp',['../d1/d9f/debug__mode_8hpp.html',1,'']]],
  ['debug_5futils_2ehpp',['debug_utils.hpp',['../d6/d32/debug__utils_8hpp.html',1,'']]],
  ['debugging_5fthe_5fsystem_2emarkdown',['debugging_the_system.markdown',['../da/d69/debugging__the__system_8markdown.html',1,'']]],
  ['defines_2eh',['defines.h',['../d8/db0/defines_8h.html',1,'']]],
  ['depth_2ehpp',['depth.hpp',['../db/d30/depth_8hpp.html',1,'']]],
  ['deriche_5ffilter_2ehpp',['deriche_filter.hpp',['../d4/d71/deriche__filter_8hpp.html',1,'']]],
  ['deriv_2ehpp',['deriv.hpp',['../df/d27/expr_2deriv_8hpp.html',1,'(Global Namespace)'],['../dd/da3/ptr2d_2deriv_8hpp.html',1,'(Global Namespace)']]],
  ['descriptor_2ehpp',['descriptor.hpp',['../db/d82/line__descriptor_2include_2opencv2_2line__descriptor_2descriptor_8hpp.html',1,'(Global Namespace)'],['../d8/db0/stereo_2include_2opencv2_2stereo_2descriptor_8hpp.html',1,'(Global Namespace)']]],
  ['desync_2ehpp',['desync.hpp',['../dd/d25/desync_8hpp.html',1,'']]],
  ['detection_5fbased_5ftracker_2ehpp',['detection_based_tracker.hpp',['../d5/d5a/detection__based__tracker_8hpp.html',1,'']]],
  ['detection_5fof_5fplanar_5fobjects_2emarkdown',['detection_of_planar_objects.markdown',['../dd/d5c/detection__of__planar__objects_8markdown.html',1,'']]],
  ['dev_5fwith_5focv_5fon_5fandroid_2emarkdown',['dev_with_OCV_on_Android.markdown',['../d9/d37/dev__with__OCV__on__Android_8markdown.html',1,'']]],
  ['device_5fselector_5finterface_2ehpp',['device_selector_interface.hpp',['../d1/de2/device__selector__interface_8hpp.html',1,'']]],
  ['dict_2ehpp',['dict.hpp',['../df/de6/dict_8hpp.html',1,'']]],
  ['dictionary_2ehpp',['dictionary.hpp',['../dc/df7/dictionary_8hpp.html',1,'']]],
  ['directx_2ehpp',['directx.hpp',['../df/d8b/directx_8hpp.html',1,'']]],
  ['discrete_5ffourier_5ftransform_2emarkdown',['discrete_fourier_transform.markdown',['../d7/d0e/discrete__fourier__transform_8markdown.html',1,'']]],
  ['disparity_5ffilter_2ehpp',['disparity_filter.hpp',['../da/d08/disparity__filter_8hpp.html',1,'']]],
  ['disparity_5ffiltering_2emarkdown',['disparity_filtering.markdown',['../d1/de3/disparity__filtering_8markdown.html',1,'']]],
  ['display_5fimage_2emarkdown',['display_image.markdown',['../dd/d8a/display__image_8markdown.html',1,'']]],
  ['dist_2eh',['dist.h',['../d1/d82/dist_8h.html',1,'']]],
  ['distance_5ftransform_2emarkdown',['distance_transform.markdown',['../dc/d15/distance__transform_8markdown.html',1,'']]],
  ['dmatch_2ehpp',['dmatch.hpp',['../d7/de1/dmatch_8hpp.html',1,'']]],
  ['dnn_2ehpp',['dnn.hpp',['../db/ddc/dnn_2dnn_8hpp.html',1,'(Global Namespace)'],['../d9/d8c/dnn_8hpp.html',1,'(Global Namespace)']]],
  ['dnn_5fandroid_2emarkdown',['dnn_android.markdown',['../de/d6f/dnn__android_8markdown.html',1,'']]],
  ['dnn_5fcustom_5flayers_2emd',['dnn_custom_layers.md',['../d6/ddf/dnn__custom__layers_8md.html',1,'']]],
  ['dnn_5fface_2emarkdown',['dnn_face.markdown',['../df/dd1/dnn__face_8markdown.html',1,'']]],
  ['dnn_5fgooglenet_2emarkdown',['dnn_googlenet.markdown',['../dc/d31/dnn__googlenet_8markdown.html',1,'']]],
  ['dnn_5fhalide_2emarkdown',['dnn_halide.markdown',['../d0/d59/dnn__halide_8markdown.html',1,'']]],
  ['dnn_5fhalide_5fscheduling_2emarkdown',['dnn_halide_scheduling.markdown',['../d6/d74/dnn__halide__scheduling_8markdown.html',1,'']]],
  ['dnn_5fjavascript_2emarkdown',['dnn_javascript.markdown',['../da/d1b/dnn__javascript_8markdown.html',1,'']]],
  ['dnn_5fobjdetect_5ftutorial_2emarkdown',['dnn_objdetect_tutorial.markdown',['../dd/d87/dnn__objdetect__tutorial_8markdown.html',1,'']]],
  ['dnn_5focr_2emarkdown',['dnn_OCR.markdown',['../de/dff/dnn__OCR_8markdown.html',1,'']]],
  ['dnn_5fsuperres_2ehpp',['dnn_superres.hpp',['../d3/db0/dnn__superres_8hpp.html',1,'']]],
  ['dnn_5ftext_5fspotting_2emarkdown',['dnn_text_spotting.markdown',['../d8/d94/dnn__text__spotting_8markdown.html',1,'']]],
  ['dnn_5fyolo_2emarkdown',['dnn_yolo.markdown',['../dd/dfb/dnn__yolo_8markdown.html',1,'']]],
  ['documentation_5ftutorial_2emarkdown',['documentation_tutorial.markdown',['../d6/d6b/documentation__tutorial_8markdown.html',1,'']]],
  ['dpm_2ehpp',['dpm.hpp',['../da/d8a/dpm_8hpp.html',1,'']]],
  ['dualquaternion_2ehpp',['dualquaternion.hpp',['../d2/dfa/dualquaternion_8hpp.html',1,'']]],
  ['dummy_2eh',['dummy.h',['../d2/d94/dummy_8h.html',1,'']]],
  ['dynafu_2ehpp',['dynafu.hpp',['../dc/dcf/dynafu_8hpp.html',1,'']]],
  ['dynamic_5fbitset_2eh',['dynamic_bitset.h',['../da/d5c/dynamic__bitset_8h.html',1,'']]],
  ['dynamic_5fsmem_2ehpp',['dynamic_smem.hpp',['../d3/d73/modules_2core_2include_2opencv2_2core_2cuda_2dynamic__smem_8hpp.html',1,'(Global Namespace)'],['../d1/d15/contrib_2modules_2cudev_2include_2opencv2_2cudev_2block_2dynamic__smem_8hpp.html',1,'(Global Namespace)']]]
];
