var searchData=
[
  ['icp_2ehpp',['icp.hpp',['../d3/d94/icp_8hpp.html',1,'']]],
  ['ie_2ehpp',['ie.hpp',['../df/d70/ie_8hpp.html',1,'']]],
  ['image_5fmanipulation_2emarkdown',['image_manipulation.markdown',['../d6/dd9/image__manipulation_8markdown.html',1,'']]],
  ['img_5fhash_2ehpp',['img_hash.hpp',['../d4/d59/img__hash_8hpp.html',1,'']]],
  ['img_5fhash_5fbase_2ehpp',['img_hash_base.hpp',['../d9/db6/img__hash__base_8hpp.html',1,'']]],
  ['imgcodecs_2ehpp',['imgcodecs.hpp',['../d7/dd8/imgcodecs_2imgcodecs_8hpp.html',1,'(Global Namespace)'],['../d6/d87/imgcodecs_8hpp.html',1,'(Global Namespace)']]],
  ['imgproc_2ehpp',['imgproc.hpp',['../dd/d01/imgproc_2include_2opencv2_2imgproc_2imgproc_8hpp.html',1,'(Global Namespace)'],['../d1/d4f/imgproc_2include_2opencv2_2imgproc_8hpp.html',1,'(Global Namespace)'],['../d0/d08/gapi_2include_2opencv2_2gapi_2cpu_2imgproc_8hpp.html',1,'(Global Namespace)'],['../de/da0/gapi_2include_2opencv2_2gapi_2fluid_2imgproc_8hpp.html',1,'(Global Namespace)'],['../d8/d8e/gapi_2include_2opencv2_2gapi_2gpu_2imgproc_8hpp.html',1,'(Global Namespace)'],['../d4/d75/gapi_2include_2opencv2_2gapi_2imgproc_8hpp.html',1,'(Global Namespace)'],['../d9/dca/gapi_2include_2opencv2_2gapi_2ocl_2imgproc_8hpp.html',1,'(Global Namespace)']]],
  ['index_5ftesting_2eh',['index_testing.h',['../db/dd9/index__testing_8h.html',1,'']]],
  ['infer_2ehpp',['infer.hpp',['../d6/d32/infer_8hpp.html',1,'(Global Namespace)'],['../d8/db1/oak_2infer_8hpp.html',1,'(Global Namespace)']]],
  ['inference_5fengine_2ehpp',['inference_engine.hpp',['../d8/dcd/inference__engine_8hpp.html',1,'']]],
  ['inpainting_2ehpp',['inpainting.hpp',['../dc/dc7/videostab_2include_2opencv2_2videostab_2inpainting_8hpp.html',1,'(Global Namespace)'],['../d7/d72/xphoto_2include_2opencv2_2xphoto_2inpainting_8hpp.html',1,'(Global Namespace)']]],
  ['inpainting_2emarkdown',['inpainting.markdown',['../d0/d0f/inpainting_8markdown.html',1,'']]],
  ['install_5ftesseract_2emarkdown',['install_tesseract.markdown',['../de/d5b/install__tesseract_8markdown.html',1,'']]],
  ['instrumentation_2ehpp',['instrumentation.hpp',['../df/dab/instrumentation_8hpp.html',1,'']]],
  ['integral_2ehpp',['integral.hpp',['../d3/da8/integral_8hpp.html',1,'']]],
  ['intelperc_2emarkdown',['intelperc.markdown',['../d8/d80/intelperc_8markdown.html',1,'']]],
  ['intensity_5ftransform_2ehpp',['intensity_transform.hpp',['../da/d3c/intensity__transform_8hpp.html',1,'']]],
  ['interactive_5fcalibration_2emarkdown',['interactive_calibration.markdown',['../df/dc3/interactive__calibration_8markdown.html',1,'']]],
  ['interactive_5fface_5fdetection_2emarkdown',['interactive_face_detection.markdown',['../d7/dda/interactive__face__detection_8markdown.html',1,'']]],
  ['interface_2eh',['interface.h',['../d2/d10/core_2include_2opencv2_2core_2hal_2interface_8h.html',1,'(Global Namespace)'],['../d5/d1e/imgproc_2include_2opencv2_2imgproc_2hal_2interface_8h.html',1,'(Global Namespace)'],['../d9/d0a/features2d_2include_2opencv2_2features2d_2hal_2interface_8h.html',1,'(Global Namespace)']]],
  ['interpolation_2ehpp',['interpolation.hpp',['../d8/d8e/interpolation_8hpp.html',1,'']]],
  ['intrin_2ehpp',['intrin.hpp',['../df/db4/intrin_8hpp.html',1,'']]],
  ['intrin_5favx_2ehpp',['intrin_avx.hpp',['../d9/dd4/intrin__avx_8hpp.html',1,'']]],
  ['intrin_5favx512_2ehpp',['intrin_avx512.hpp',['../d1/dc3/intrin__avx512_8hpp.html',1,'']]],
  ['intrin_5fcpp_2ehpp',['intrin_cpp.hpp',['../d1/d94/intrin__cpp_8hpp.html',1,'']]],
  ['intrin_5fforward_2ehpp',['intrin_forward.hpp',['../da/daa/intrin__forward_8hpp.html',1,'']]],
  ['intrin_5fmsa_2ehpp',['intrin_msa.hpp',['../dd/d08/intrin__msa_8hpp.html',1,'']]],
  ['intrin_5fneon_2ehpp',['intrin_neon.hpp',['../dd/d52/intrin__neon_8hpp.html',1,'']]],
  ['intrin_5frvv_2ehpp',['intrin_rvv.hpp',['../d8/dfb/intrin__rvv_8hpp.html',1,'']]],
  ['intrin_5frvv071_2ehpp',['intrin_rvv071.hpp',['../d0/d2f/intrin__rvv071_8hpp.html',1,'']]],
  ['intrin_5fsse_2ehpp',['intrin_sse.hpp',['../d2/d3c/intrin__sse_8hpp.html',1,'']]],
  ['intrin_5fsse_5fem_2ehpp',['intrin_sse_em.hpp',['../d3/d95/intrin__sse__em_8hpp.html',1,'']]],
  ['intrin_5fvsx_2ehpp',['intrin_vsx.hpp',['../d3/d96/intrin__vsx_8hpp.html',1,'']]],
  ['intrin_5fwasm_2ehpp',['intrin_wasm.hpp',['../de/df3/intrin__wasm_8hpp.html',1,'']]],
  ['intrinsics_2ehpp',['intrinsics.hpp',['../d7/d65/intrinsics_8hpp.html',1,'']]],
  ['intro_2emarkdown',['intro.markdown',['../d0/d2e/intro_8markdown.html',1,'']]],
  ['introduction_5fto_5fpca_2emarkdown',['introduction_to_pca.markdown',['../de/d8a/introduction__to__pca_8markdown.html',1,'']]],
  ['introduction_5fto_5fsvm_2emarkdown',['introduction_to_svm.markdown',['../d7/d6d/introduction__to__svm_8markdown.html',1,'']]],
  ['io_2ehpp',['io.hpp',['../d2/dc6/io_8hpp.html',1,'']]],
  ['ios_2eh',['ios.h',['../df/dd5/ios_8h.html',1,'']]],
  ['ios_5finstall_2emarkdown',['ios_install.markdown',['../d2/dc6/ios__install_8markdown.html',1,'']]],
  ['ir_5faffine_2ehpp',['ir_affine.hpp',['../d8/d32/ir__affine_8hpp.html',1,'']]],
  ['ir_5frobot_2ehpp',['ir_robot.hpp',['../d4/d5f/ir__robot_8hpp.html',1,'']]],
  ['is_5fbsds_2ehpp',['is_bsds.hpp',['../df/d12/is__bsds_8hpp.html',1,'']]],
  ['is_5fweizmann_2ehpp',['is_weizmann.hpp',['../d3/db5/is__weizmann_8hpp.html',1,'']]]
];
