var searchData=
[
  ['hal_2ehpp',['hal.hpp',['../de/d0c/core_2include_2opencv2_2core_2hal_2hal_8hpp.html',1,'(Global Namespace)'],['../d4/d44/imgproc_2include_2opencv2_2imgproc_2hal_2hal_8hpp.html',1,'(Global Namespace)']]],
  ['hal_5freplacement_2ehpp',['hal_replacement.hpp',['../db/ddd/core_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['../df/d91/imgproc_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)'],['../d2/dd9/features2d_2src_2hal__replacement_8hpp.html',1,'(Global Namespace)']]],
  ['harris_5fdetector_2emarkdown',['harris_detector.markdown',['../db/d48/harris__detector_8markdown.html',1,'']]],
  ['hdf_2ehpp',['hdf.hpp',['../d7/d55/hdf_8hpp.html',1,'']]],
  ['hdf5_2eh',['hdf5.h',['../db/d87/hdf5_8h.html',1,'']]],
  ['hdf5_2ehpp',['hdf5.hpp',['../de/d24/hdf5_8hpp.html',1,'']]],
  ['hdr_5fimaging_2emarkdown',['hdr_imaging.markdown',['../d9/d87/hdr__imaging_8markdown.html',1,'']]],
  ['heap_2eh',['heap.h',['../da/ddb/heap_8h.html',1,'']]],
  ['hello_2emarkdown',['hello.markdown',['../da/da0/hello_8markdown.html',1,'']]],
  ['hfs_2ehpp',['hfs.hpp',['../de/d29/hfs_8hpp.html',1,'']]],
  ['hierarchical_5fclustering_5findex_2eh',['hierarchical_clustering_index.h',['../de/d1d/hierarchical__clustering__index_8h.html',1,'']]],
  ['highgui_2ehpp',['highgui.hpp',['../d0/dce/highgui_2highgui_8hpp.html',1,'(Global Namespace)'],['../d4/dd5/highgui_8hpp.html',1,'(Global Namespace)']]],
  ['highgui_5fwinrt_2ehpp',['highgui_winrt.hpp',['../d9/d22/highgui__winrt_8hpp.html',1,'']]],
  ['hist_5fcost_2ehpp',['hist_cost.hpp',['../df/d08/hist__cost_8hpp.html',1,'']]],
  ['histo3d_2emarkdown',['histo3D.markdown',['../df/dd7/histo3D_8markdown.html',1,'']]],
  ['histogram_2ehpp',['histogram.hpp',['../d5/d6e/histogram_8hpp.html',1,'']]],
  ['histogram_5fcalculation_2emarkdown',['histogram_calculation.markdown',['../d2/d3a/histogram__calculation_8markdown.html',1,'']]],
  ['histogram_5fcomparison_2emarkdown',['histogram_comparison.markdown',['../de/d12/histogram__comparison_8markdown.html',1,'']]],
  ['histogram_5fequalization_2emarkdown',['histogram_equalization.markdown',['../db/de8/histogram__equalization_8markdown.html',1,'']]],
  ['histogramphaseunwrapping_2ehpp',['histogramphaseunwrapping.hpp',['../df/dce/histogramphaseunwrapping_8hpp.html',1,'']]],
  ['hitormiss_2emarkdown',['hitOrMiss.markdown',['../d2/dbf/hitOrMiss_8markdown.html',1,'']]],
  ['homography_2emarkdown',['homography.markdown',['../d2/dc8/homography_8markdown.html',1,'']]],
  ['hough_5fcircle_2emarkdown',['hough_circle.markdown',['../d4/d67/hough__circle_8markdown.html',1,'']]],
  ['hough_5flines_2emarkdown',['hough_lines.markdown',['../da/d5a/hough__lines_8markdown.html',1,'']]],
  ['how_5fto_5fcreate_5fgroups_2emarkdown',['how_to_create_groups.markdown',['../d7/d7b/how__to__create__groups_8markdown.html',1,'']]],
  ['how_5fto_5fscan_5fimages_2emarkdown',['how_to_scan_images.markdown',['../d5/d91/how__to__scan__images_8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5f_2emarkdown',['how_to_use_OpenCV_parallel_for_.markdown',['../d5/d45/how__to__use__OpenCV__parallel__for___8markdown.html',1,'']]],
  ['how_5fto_5fuse_5fopencv_5fparallel_5ffor_5fnew_2emarkdown',['how_to_use_OpenCV_parallel_for_new.markdown',['../d4/d19/how__to__use__OpenCV__parallel__for__new_8markdown.html',1,'']]],
  ['hpe_5fhumaneva_2ehpp',['hpe_humaneva.hpp',['../d8/da7/hpe__humaneva_8hpp.html',1,'']]],
  ['hpe_5fparse_2ehpp',['hpe_parse.hpp',['../da/da9/hpe__parse_8hpp.html',1,'']]],
  ['hull_2emarkdown',['hull.markdown',['../d0/dbd/hull_8markdown.html',1,'']]],
  ['hwaccel_2edoc_2ehpp',['hwaccel.doc.hpp',['../d5/d5b/hwaccel_8doc_8hpp.html',1,'']]]
];
