var searchData=
[
  ['singular_20value_20matrix_20decomposition',['Singular value matrix decomposition',['../dd/d2a/group__core__hal__interface__decomp__svd.html',1,'']]],
  ['square_20root_20calculation',['Square root calculation',['../d5/dc3/group__core__hal__interface__sqrt.html',1,'']]],
  ['softfloat_20support',['Softfloat support',['../d7/dcc/group__core__utils__softfloat.html',1,'']]],
  ['sse_20utilities',['SSE utilities',['../d6/d06/group__core__utils__sse.html',1,'']]],
  ['stereo_20correspondence',['Stereo Correspondence',['../dd/d47/group__cudastereo.html',1,'']]],
  ['slam',['SLAM',['../dc/dfb/group__datasets__slam.html',1,'']]],
  ['super_20resolution',['Super Resolution',['../d1/d5b/group__datasets__sr.html',1,'']]],
  ['structural_20analysis_20and_20shape_20descriptors',['Structural Analysis and Shape Descriptors',['../d3/dc0/group__imgproc__shape.html',1,'']]],
  ['seamless_20cloning',['Seamless Cloning',['../df/da0/group__photo__clone.html',1,'']]],
  ['silhouette_20based_203d_20object_20tracking',['silhouette based 3D object tracking',['../d4/dc4/group__rapid.html',1,'']]],
  ['saliency_20api',['Saliency API',['../d8/d65/group__saliency.html',1,'']]],
  ['structure_20from_20motion',['Structure From Motion',['../d8/d8c/group__sfm.html',1,'']]],
  ['shape_20distance_20and_20matching',['Shape Distance and Matching',['../d1/d85/group__shape.html',1,'']]],
  ['simple_20pipeline',['Simple Pipeline',['../d7/de2/group__simple__pipeline.html',1,'']]],
  ['stereo_20correspondance_20algorithms',['Stereo Correspondance Algorithms',['../dd/d86/group__stereo.html',1,'']]],
  ['seam_20estimation',['Seam Estimation',['../d9/d24/group__stitching__seam.html',1,'']]],
  ['structured_20light_20api',['Structured Light API',['../d1/d90/group__structured__light.html',1,'']]],
  ['super_20resolution',['Super Resolution',['../d7/d0a/group__superres.html',1,'']]],
  ['surface_20matching',['Surface Matching',['../d9/d25/group__surface__matching.html',1,'']]],
  ['scene_20text_20detection_20and_20recognition',['Scene Text Detection and Recognition',['../d4/d61/group__text.html',1,'']]],
  ['scene_20text_20detection',['Scene Text Detection',['../da/d56/group__text__detect.html',1,'']]],
  ['scene_20text_20recognition',['Scene Text Recognition',['../d8/df2/group__text__recognize.html',1,'']]],
  ['structured_20forests_20for_20fast_20edge_20detection',['Structured forests for fast edge detection',['../de/d51/group__ximgproc__edge.html',1,'']]],
  ['superpixels',['Superpixels',['../df/d6c/group__ximgproc__superpixel.html',1,'']]]
];
