var searchData=
[
  ['camera_20calibration_20and_203d_20reconstruction',['Camera Calibration and 3D Reconstruction',['../d9/d0c/group__calib3d.html',1,'']]],
  ['c_20api',['C API',['../d5/db8/group__calib3d__c.html',1,'']]],
  ['custom_20calibration_20pattern_20for_203d_20reconstruction',['Custom Calibration Pattern for 3D reconstruction',['../d3/ddc/group__ccalib.html',1,'']]],
  ['color_20correction_20model',['Color Correction Model',['../de/df4/group__color__correction.html',1,'']]],
  ['conditioning',['Conditioning',['../da/d8b/group__conditioning.html',1,'']]],
  ['core_20functionality',['Core functionality',['../d0/de1/group__core.html',1,'']]],
  ['c_20structures_20and_20operations',['C structures and operations',['../d2/df8/group__core__c.html',1,'']]],
  ['connections_20with_20c_2b_2b',['Connections with C++',['../d8/dd7/group__core__c__glue.html',1,'']]],
  ['clustering',['Clustering',['../d5/d38/group__core__cluster.html',1,'']]],
  ['cholesky_20matrix_20decomposition',['Cholesky matrix decomposition',['../d8/d0e/group__core__hal__interface__decomp__cholesky.html',1,'']]],
  ['channel_20merge',['Channel merge',['../df/d2e/group__core__hal__interface__merge.html',1,'']]],
  ['channel_20split',['Channel split',['../df/df2/group__core__hal__interface__split.html',1,'']]],
  ['cuda_2daccelerated_20computer_20vision',['CUDA-accelerated Computer Vision',['../d1/d1e/group__cuda.html',1,'']]],
  ['core_20operations_20on_20matrices',['Core Operations on Matrices',['../de/d09/group__cudaarithm__core.html',1,'']]],
  ['core_20part',['Core part',['../d7/d05/group__cudacore.html',1,'']]],
  ['color_20space_20processing',['Color space processing',['../db/d8c/group__cudaimgproc__color.html',1,'']]],
  ['clustering_20and_20search_20in_20multi_2ddimensional_20spaces',['Clustering and Search in Multi-Dimensional Spaces',['../dc/de5/group__flann.html',1,'']]],
  ['c_20api',['C API',['../d0/d28/group__highgui__c.html',1,'']]],
  ['c_20api',['C API',['../da/d0a/group__imgcodecs__c.html',1,'']]],
  ['c_20api',['C API',['../df/d4e/group__imgproc__c.html',1,'']]],
  ['color_20space_20conversions',['Color Space Conversions',['../d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['colormaps_20in_20opencv',['ColorMaps in OpenCV',['../d3/d50/group__imgproc__colormap.html',1,'']]],
  ['cascade_20classifier_20for_20object_20detection',['Cascade Classifier for Object Detection',['../de/d37/group__objdetect__cascade__classifier.html',1,'']]],
  ['common_20functions_20and_20classes',['Common functions and classes',['../de/de1/group__objdetect__common.html',1,'']]],
  ['computational_20photography',['Computational Photography',['../d1/d0d/group__photo.html',1,'']]],
  ['c_20api',['C API',['../d3/d40/group__photo__c.html',1,'']]],
  ['contrast_20preserving_20decolorization',['Contrast Preserving Decolorization',['../d4/d32/group__photo__decolor.html',1,'']]],
  ['c_20api',['C API',['../d3/d12/group__video__c.html',1,'']]],
  ['c_20api_20for_20video_20i_2fo',['C API for video I/O',['../dd/d01/group__videoio__c.html',1,'']]]
];
