var searchData=
[
  ['gui_20for_20interactive_20visual_20debugging_20of_20computer_20vision_20programs',['GUI for Interactive Visual Debugging of Computer Vision Programs',['../df/dff/group__cvv.html',1,'']]],
  ['gesture_20recognition',['Gesture Recognition',['../d9/db7/group__datasets__gr.html',1,'']]],
  ['g_2dapi_20framework',['G-API framework',['../d7/d0d/group__gapi.html',1,'']]],
  ['graph_20api_3a_20converting_20image_20from_20one_20color_20space_20to_20another',['Graph API: Converting image from one color space to another',['../dc/d38/group__gapi__colorconvert.html',1,'']]],
  ['g_2dapi_20graph_20compilation_20arguments',['G-API Graph Compilation Arguments',['../d9/d29/group__gapi__compile__args.html',1,'']]],
  ['g_2dapi_20core_20functionality',['G-API Core functionality',['../df/d1f/group__gapi__core.html',1,'']]],
  ['g_2dapi_20data_20types',['G-API Data Types',['../db/df1/group__gapi__data__objects.html',1,'']]],
  ['gapi_5fdata_5fstructures',['Gapi_data_structures',['../d9/d51/group__gapi__data__structures.html',1,'']]],
  ['g_2dapi_20drawing_20and_20composition_20functionality',['G-API Drawing and composition functionality',['../df/de4/group__gapi__draw.html',1,'']]],
  ['graph_20api_3a_20image_20feature_20detection',['Graph API: Image Feature Detection',['../d5/def/group__gapi__feature.html',1,'']]],
  ['graph_20api_3a_20image_20filters',['Graph API: Image filters',['../da/dc5/group__gapi__filters.html',1,'']]],
  ['g_2dapi_20image_20processing_20functionality',['G-API Image processing functionality',['../d2/d00/group__gapi__imgproc.html',1,'']]],
  ['g_2dapi_20main_20classes',['G-API Main Classes',['../d8/dd0/group__gapi__main__classes.html',1,'']]],
  ['graph_20api_3a_20math_20operations',['Graph API: Math operations',['../da/dd3/group__gapi__math.html',1,'']]],
  ['graph_20api_3a_20operations_20on_20matrices',['Graph API: Operations on matrices',['../d0/d86/group__gapi__matrixop.html',1,'']]],
  ['g_2dapi_20metadata_20descriptors',['G-API Metadata Descriptors',['../d3/d0c/group__gapi__meta__args.html',1,'']]],
  ['graph_20api_3a_20pixelwise_20operations',['Graph API: Pixelwise operations',['../d1/db2/group__gapi__pixelwise.html',1,'']]],
  ['g_2dapi_20serialization_20functionality',['G-API Serialization functionality',['../db/d06/group__gapi__serialization.html',1,'']]],
  ['graph_20api_3a_20image_20structural_20analysis_20and_20shape_20descriptors',['Graph API: Image Structural Analysis and Shape Descriptors',['../d3/d01/group__gapi__shape.html',1,'']]],
  ['g_2dapi_20standard_20backends',['G-API Standard Backends',['../dc/d1c/group__gapi__std__backends.html',1,'']]],
  ['graph_20api_3a_20image_20and_20channel_20composition_20functions',['Graph API: Image and channel composition functions',['../d6/d91/group__gapi__transform.html',1,'']]],
  ['g_2dapi_20video_20processing_20functionality',['G-API Video processing functionality',['../d4/d55/group__gapi__video.html',1,'']]],
  ['geometric_20image_20transformations',['Geometric Image Transformations',['../da/d54/group__imgproc__transform.html',1,'']]],
  ['global_20motion_20estimation',['Global Motion Estimation',['../d4/d2c/group__videostab__motion.html',1,'']]]
];
