var searchData=
[
  ['opencv_20modules',['OpenCV modules',['../index.html',1,'']]],
  ['opencv_20configuration_20options_20reference',['OpenCV configuration options reference',['../db/d05/tutorial_config_reference.html',1,'tutorial_table_of_content_introduction']]],
  ['object_20detection_20using_20cnns',['Object Detection using CNNs',['../d2/da2/tutorial_dnn_objdetect.html',1,'tutorial_contrib_root']]],
  ['opencv_20installation_20overview',['OpenCV installation overview',['../d0/d3d/tutorial_general_install.html',1,'tutorial_table_of_content_introduction']]],
  ['opencv_20ios_20hello',['OpenCV iOS Hello',['../d7/d88/tutorial_hello.html',1,'tutorial_table_of_content_ios']]],
  ['opencv_20ios_20_2d_20image_20processing',['OpenCV iOS - Image Processing',['../d3/def/tutorial_image_manipulation.html',1,'tutorial_table_of_content_ios']]],
  ['optical_20flow',['Optical Flow',['../db/d7f/tutorial_js_lucas_kanade.html',1,'tutorial_js_table_of_contents_video']]],
  ['object_20detection_20example',['Object Detection Example',['../d0/d0f/tutorial_js_object_detection.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['object_20detection_20example_20with_20camera',['Object Detection Example with Camera',['../d2/d14/tutorial_js_object_detection_with_camera.html',1,'tutorial_js_table_of_contents_dnn']]],
  ['opencv_2ejs_20tutorials',['OpenCV.js Tutorials',['../d5/d10/tutorial_js_root.html',1,'']]],
  ['object_20detection',['Object Detection',['../dc/d73/tutorial_js_table_of_contents_objdetect.html',1,'tutorial_js_root']]],
  ['operations_20with_20images',['Operations with images',['../d5/d98/tutorial_mat_operations.html',1,'tutorial_table_of_content_core']]],
  ['opencv4android_20sdk',['OpenCV4Android SDK',['../da/d2a/tutorial_O4A_SDK.html',1,'tutorial_table_of_content_introduction']]],
  ['omnidirectional_20camera_20calibration',['Omnidirectional Camera Calibration',['../dd/d12/tutorial_omnidir_calib_main.html',1,'tutorial_contrib_root']]],
  ['optical_20flow',['Optical Flow',['../d4/dee/tutorial_optical_flow.html',1,'tutorial_table_of_content_other']]],
  ['out_2dof_2dfocus_20deblur_20filter',['Out-of-focus Deblur Filter',['../de/d3c/tutorial_out_of_focus_deblur_filter.html',1,'tutorial_table_of_content_imgproc']]],
  ['ocr_20of_20hand_2dwritten_20data_20using_20knn',['OCR of Hand-written Data using kNN',['../d8/d4b/tutorial_py_knn_opencv.html',1,'tutorial_py_knn_index']]],
  ['optical_20flow',['Optical Flow',['../d7/d8b/tutorial_py_lucas_kanade.html',1,'']]],
  ['orb_20_28oriented_20fast_20and_20rotated_20brief_29',['ORB (Oriented FAST and Rotated BRIEF)',['../d1/d89/tutorial_py_orb.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['opencv_2dpython_20tutorials',['OpenCV-Python Tutorials',['../d6/d00/tutorial_py_root.html',1,'']]],
  ['ocr_20of_20hand_2dwritten_20data_20using_20svm',['OCR of Hand-written Data using SVM',['../dd/d3b/tutorial_py_svm_opencv.html',1,'tutorial_py_svm_index']]],
  ['opencv_2dpython_20bindings',['OpenCV-Python Bindings',['../df/da2/tutorial_py_table_of_contents_bindings.html',1,'tutorial_py_root']]],
  ['object_20detection',['Object Detection',['../d9/de5/tutorial_py_table_of_contents_objdetect.html',1,'']]],
  ['opencv_20tutorials',['OpenCV Tutorials',['../d9/df8/tutorial_root.html',1,'']]],
  ['opencv_20ios',['OpenCV iOS',['../d3/dc9/tutorial_table_of_content_ios.html',1,'tutorial_root']]],
  ['object_20detection_20_28objdetect_20module_29',['Object Detection (objdetect module)',['../d2/d64/tutorial_table_of_content_objdetect.html',1,'']]],
  ['other_20tutorials_20_28ml_2c_20objdetect_2c_20photo_2c_20stitching_2c_20video_29',['Other tutorials (ml, objdetect, photo, stitching, video)',['../d3/dd5/tutorial_table_of_content_other.html',1,'tutorial_root']]],
  ['opencv_20viz',['OpenCV Viz',['../d7/df9/tutorial_table_of_content_viz.html',1,'tutorial_contrib_root']]],
  ['opencv_20ios_20_2d_20video_20processing',['OpenCV iOS - Video Processing',['../db/dc8/tutorial_video_processing.html',1,'tutorial_table_of_content_ios']]],
  ['oil_20painting_20effect',['Oil painting effect',['../dd/d8c/tutorial_xphoto_oil_painting_effect.html',1,'tutorial_contrib_root']]]
];
