var searchData=
[
  ['usac',['usac',['../d1/df1/md__build_master-contrib_docs-lin64_opencv_doc_tutorials_calib3d_usac.html',1,'']]],
  ['use_20opencl_20in_20android_20camera_20preview_20based_20cv_20application',['Use OpenCL in Android camera preview based CV application',['../d7/dbd/tutorial_android_ocl_intro.html',1,'tutorial_table_of_content_introduction']]],
  ['upscaling_20images_3a_20multi_2doutput',['Upscaling images: multi-output',['../d6/dca/tutorial_dnn_superres_upscale_image_multi.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['upscaling_20images_3a_20single_2doutput',['Upscaling images: single-output',['../d5/d29/tutorial_dnn_superres_upscale_image_single.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['upscaling_20video',['Upscaling video',['../de/d7f/tutorial_dnn_superres_upscale_video.html',1,'tutorial_table_of_content_dnn_superres']]],
  ['using_20the_20facemarkaam',['Using the FacemarkAAM',['../d5/dd8/tutorial_facemark_aam.html',1,'tutorial_table_of_content_facemark']]],
  ['using_20the_20facemark_20api',['Using the Facemark API',['../d7/dec/tutorial_facemark_usage.html',1,'tutorial_table_of_content_facemark']]],
  ['using_20a_20cv_3a_3acuda_3a_3agpumat_20with_20thrust',['Using a cv::cuda::GpuMat with thrust',['../d8/db9/tutorial_gpu_thrust_interop.html',1,'tutorial_table_of_content_gpu']]],
  ['using_20creative_20senz3d_20and_20other_20intel_20realsense_20sdk_20compatible_20depth_20sensors',['Using Creative Senz3D and other Intel RealSense SDK compatible depth sensors',['../db/d08/tutorial_intelperc.html',1,'tutorial_table_of_content_app']]],
  ['using_20opencv_20java_20with_20eclipse',['Using OpenCV Java with Eclipse',['../d1/d0a/tutorial_java_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_2ejs_20in_20node_2ejs',['Using OpenCV.js In Node.js',['../dc/de6/tutorial_js_nodejs.html',1,'tutorial_js_table_of_contents_setup']]],
  ['using_20opencv_2ejs',['Using OpenCV.js',['../d0/d84/tutorial_js_usage.html',1,'tutorial_js_table_of_contents_setup']]],
  ['using_20kinect_20and_20other_20openni_20compatible_20depth_20sensors',['Using Kinect and other OpenNI compatible depth sensors',['../d7/d6f/tutorial_kinect_openni.html',1,'tutorial_table_of_content_app']]],
  ['using_20opencv_20with_20eclipse_20_28plugin_20cdt_29',['Using OpenCV with Eclipse (plugin CDT)',['../d7/d16/tutorial_linux_eclipse.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_20with_20gcc_20and_20cmake',['Using OpenCV with gcc and CMake',['../db/df5/tutorial_linux_gcc_cmake.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20opencv_20with_20gdb_2dpowered_20ides',['Using OpenCV with gdb-powered IDEs',['../d6/d25/tutorial_linux_gdb_pretty_printer.html',1,'tutorial_table_of_content_introduction']]],
  ['using_20multitracker',['Using MultiTracker',['../d5/d07/tutorial_multitracker.html',1,'tutorial_contrib_root']]],
  ['using_20orbbec_20astra_203d_20cameras',['Using Orbbec Astra 3D cameras',['../d4/d65/tutorial_orbbec_astra.html',1,'tutorial_table_of_content_app']]],
  ['understanding_20features',['Understanding Features',['../df/d54/tutorial_py_features_meaning.html',1,'tutorial_py_table_of_contents_feature2d']]],
  ['understanding_20k_2dmeans_20clustering',['Understanding K-Means Clustering',['../de/d4d/tutorial_py_kmeans_understanding.html',1,'tutorial_py_kmeans_index']]],
  ['understanding_20k_2dnearest_20neighbour',['Understanding k-Nearest Neighbour',['../d5/d26/tutorial_py_knn_understanding.html',1,'tutorial_py_knn_index']]],
  ['understanding_20svm',['Understanding SVM',['../d4/db1/tutorial_py_svm_basics.html',1,'tutorial_py_svm_index']]],
  ['unwrap_20two_2ddimensional_20phase_20maps',['Unwrap two-dimensional phase maps',['../d9/dfb/tutorial_unwrap.html',1,'tutorial_unwrap_phase_map']]]
];
